.editorconfig
.eslintrc
.gitignore
CHANGELOG.md
PULL_REQUEST_TEMPLATE.md
README.md
package.json
src/index.js
src/settings/FeatureSettings.js
src/settings/GeneralSettings.js
src/settings/InvoiceSettings.js
src/settings/index.js
test/bigtest/.eslintrc
test/bigtest/helpers/setup-application.js
test/bigtest/index.js
test/bigtest/interactors/application.js
test/bigtest/interactors/settings.js
test/bigtest/network/boot.js
test/bigtest/network/config.js
test/bigtest/network/index.js
test/bigtest/network/scenarios/default.js
test/bigtest/tests/application-test.js
test/bigtest/tests/settings-test.js
translations/ui-invoice/en.json

Initial files, created by `stripes-cli` and config files for eslint, EditorConfig, etc.

UINV-1 project setup

---

Jenkinsfile
src/index.js

To enable CI
https://issues.folio.org/browse/UINV-1 …

UINV-1 enable CI

---

src/settings/FeatureSettings.js
src/settings/GeneralSettings.js
src/settings/InvoiceSettings.js
translations/ui-invoice/en.json

remove translation values from boilerplate pages (they might be useful still though, so let's keep them for now)
https://issues.folio.org/browse/UINV-1 …

UINV-1 remove mocked tranlsation values

---

translations/ui-invoice/ar.json
translations/ui-invoice/ca.json
translations/ui-invoice/da.json
translations/ui-invoice/de.json
translations/ui-invoice/en_GB.json
translations/ui-invoice/en_SE.json
translations/ui-invoice/en_US.json
translations/ui-invoice/es.json
translations/ui-invoice/es_419.json
translations/ui-invoice/es_ES.json
translations/ui-invoice/fr.json
translations/ui-invoice/fr_FR.json
translations/ui-invoice/hu.json
translations/ui-invoice/it_IT.json
translations/ui-invoice/pt_BR.json
translations/ui-invoice/pt_PT.json
translations/ui-invoice/zh_CN.json

Update translation strings as of 20190522T140747

---

translations/ui-invoice/pt_BR.json

Update translation strings as of 20190522T154250

---

translations/ui-invoice/ar.json

Update translation strings as of 20190523T143922

---

src/common/constants/api.js
src/common/constants/index.js
src/index.js
src/invoices/InvoicesList/InvoicesList.js
src/invoices/InvoicesList/index.js
src/invoices/index.js
test/bigtest/interactors/InvoicesList.js
test/bigtest/network/config.js
test/bigtest/network/configs/invoices.js
test/bigtest/network/factories/invoice.js
test/bigtest/network/index.js
test/bigtest/network/models/invoice.js
test/bigtest/network/serializers/base.js
test/bigtest/network/serializers/invoice.js
test/bigtest/tests/InvoicesList/InvoicesList-test.js

https://issues.folio.org/browse/UINV-4
initial config of SearchAndSort
While it's helpful …

UINV-4 Implement three pane layout for invoice UI - base view

---

package.json
src/common/constants/api.js
src/index.js
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceDetails/index.js
src/invoices/InvoicesList/Invoice/Invoice.js
src/invoices/InvoicesList/Invoice/InvoiceDetailsLayer.js
src/invoices/InvoicesList/Invoice/index.js
src/invoices/InvoicesList/InvoicesList.js
test/bigtest/interactors/InvoiceDetails.js
test/bigtest/network/configs/invoices.js
test/bigtest/tests/InvoiceDetails/InvoiceDetails-test.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-4
viewRecordComponent
While it's helpful for reviewers …

UINV-4 three pane layout - details structure

---

.eslintrc
package.json

To not push `.only` tests, it will be marked red in IDE and build will be failed if they are pushed …

no `.only` tests eslint rule

---

package.json
src/common/constants/api.js
src/common/constants/constants.js
src/common/constants/index.js
src/common/resources/base.js
src/common/resources/index.js
src/common/resources/vendor.js
src/common/utils/index.js
src/common/utils/invoiceUtils.js
src/invoices/InvoicesList/InvoicesList.js
test/bigtest/interactors/InvoicesList.js
test/bigtest/network/config.js
test/bigtest/network/configs/vendors.js
test/bigtest/network/factories/invoice.js
test/bigtest/network/factories/vendor.js
test/bigtest/network/models/vendor.js
test/bigtest/network/scenarios/default.js
test/bigtest/network/serializers/vendor.js
test/bigtest/tests/InvoicesList/InvoicesList-test.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-4
SearchAndSort configuration …

UINV-4 three panes layout - columns

---

translations/ui-invoice/ar.json
translations/ui-invoice/ca.json
translations/ui-invoice/da.json
translations/ui-invoice/de.json
translations/ui-invoice/en_GB.json
translations/ui-invoice/en_SE.json
translations/ui-invoice/en_US.json
translations/ui-invoice/es.json
translations/ui-invoice/es_419.json
translations/ui-invoice/es_ES.json
translations/ui-invoice/fr.json
translations/ui-invoice/fr_FR.json
translations/ui-invoice/hu.json
translations/ui-invoice/it_IT.json
translations/ui-invoice/pt_BR.json
translations/ui-invoice/pt_PT.json
translations/ui-invoice/zh_CN.json

Update translation strings as of 20190609T200038

---

package.json
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoiceForm/index.js
src/invoices/InvoicesList/InvoicesList.js
test/bigtest/interactors/InvoiceFormInteractor.js
test/bigtest/interactors/InvoicesList.js
test/bigtest/network/configs/invoices.js
test/bigtest/tests/InvoiceEdit/invoice-create-test.js
test/bigtest/tests/InvoicesList/InvoicesList-test.js
translations/ui-invoice/en.json

Initial implementation of Create invoice form
https://issues.folio.org/browse/UINV-3
While …

UINV-3 - create invoice

---

package.json
src/common/LoadingPane/LoadingPane.js
src/invoices/InvoiceDetails/ActionMenu.js
src/invoices/InvoiceDetails/Information/Information.js
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoicesList/Invoice/Invoice.js
src/invoices/InvoicesList/Invoice/InvoiceDetailsLayer.js
src/invoices/InvoicesList/Invoice/InvoiceEditLayer.js
src/invoices/InvoicesList/InvoicesList.js
test/bigtest/interactors/InvoiceFormInteractor.js
test/bigtest/network/configs/invoices.js
test/bigtest/network/factories/invoice.js
test/bigtest/tests/InvoiceEdit/invoice-edit-test.js
translations/ui-invoice/en.json

Edit invoice form initial components and save logic
https://issues.folio.org/browse/UINV-3 …

UINV-3 Edit invoice form initial

---

package.json
src/invoices/InvoiceDetails/Information/Information.js
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceForm/InvoiceForm.js

Fixed permissions and interfaces, metadata section
https://issues.folio.org/browse/UINV-3 …

UINV-3 fix permissions and Metadata section

---

src/common/constants/constants.js
src/invoices/InvoiceForm/InvoiceForm.js

Create and save invoice details - select Vendor by code
We need to filter on `isVendor` and `status === 'Active'`
https://issues.folio.org/browse/UINV-16
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as …

UINV-16 select Vendor by code

---

src/common/utils/index.js
src/common/utils/parseAddressConfigs.js
src/invoices/InvoiceDetails/ActionMenu.js
src/invoices/InvoiceForm/InvoiceForm.js

Fix bill to address selection
https://issues.folio.org/browse/UINV-3 …

UINV-3 fix billTo address

---

src/common/constants/api.js
src/common/resources/index.js
src/common/resources/invoice.js
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceDetails/LineButtons.js
src/invoices/InvoiceLineForm/InvoiceLineForm.js
src/invoices/InvoiceLineForm/index.js
src/invoices/InvoicesList/Invoice/Invoice.js
src/invoices/InvoicesList/Invoice/InvoiceDetailsLayer.js
src/invoices/InvoicesList/InvoiceLine/InvoiceLine.js
src/invoices/InvoicesList/InvoiceLine/InvoiceLineDetailsLayer.js
src/invoices/InvoicesList/InvoiceLine/InvoiceLineEditLayer.js
test/bigtest/interactors/InvoiceDetails.js
test/bigtest/interactors/InvoiceLineFormInteractor.js
test/bigtest/interactors/TextFieldInteractor.js
test/bigtest/network/config.js
test/bigtest/network/configs/invoices.js
test/bigtest/network/configs/lines.js
test/bigtest/network/factories/line.js
test/bigtest/network/models/line.js
test/bigtest/network/serializers/line.js
test/bigtest/tests/InvoiceDetails/InvoiceDetails-test.js
test/bigtest/tests/InvoiceLine/invoice-line-edit-test.js
translations/ui-invoice/en.json

Base routes to create, edit and view details of Invoice Line
https://issues.folio.org/browse/UINV-5 …

UINV-5 create invoice line routes

---

translations/ui-invoice/ar.json
translations/ui-invoice/ca.json
translations/ui-invoice/da.json
translations/ui-invoice/de.json
translations/ui-invoice/en_GB.json
translations/ui-invoice/en_SE.json
translations/ui-invoice/en_US.json
translations/ui-invoice/es.json
translations/ui-invoice/es_419.json
translations/ui-invoice/es_ES.json
translations/ui-invoice/fr.json
translations/ui-invoice/fr_FR.json
translations/ui-invoice/hu.json
translations/ui-invoice/it_IT.json
translations/ui-invoice/pt_BR.json
translations/ui-invoice/pt_PT.json
translations/ui-invoice/zh_CN.json

Update translation strings as of 20190624T123511

---

src/common/constants/constants.js
src/common/resources/invoice.js
src/common/utils/index.js
src/common/utils/toggleSection.js
src/invoices/AdjustmentsForm/AdjustmentsForm.js
src/invoices/AdjustmentsForm/index.js
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoiceLineForm/InvoiceLineForm.js
src/invoices/InvoicesList/InvoiceLine/InvoiceLine.js
src/invoices/InvoicesList/InvoiceLine/InvoiceLineEditLayer.js
test/bigtest/interactors/InvoiceLineFormInteractor.js
test/bigtest/tests/InvoiceLine/invoice-line-create-test.js
test/bigtest/tests/InvoiceLine/invoice-line-edit-test.js
translations/ui-invoice/en.json

Working flow for create and edit invoice lines, fund distribution is a stub for now. 
https://issues.folio.org/browse/UINV-5 …

UINV-5 Create and Edit Invoice form

---

src/common/components/FieldSelection/FieldSelection.js
test/bigtest/network/factories/vendor.js

Somehow common's component filtering code doesn't work as expected:
`dataOptions.filter(o => new RegExp(`^${e.target.value}`, 'i').test(o.label));`
So we need our filter function
https://issues.folio.org/browse/UINV-16 …

UINV-16 fix filtering vendor by code

---

src/common/utils/toggleSection.js
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLines.js
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoiceLineDetails/ActionMenu.js
src/invoices/InvoiceLineDetails/InvoiceLineDetails.js
src/invoices/InvoiceLineDetails/InvoiceLineInformation.js
src/invoices/InvoiceLineDetails/index.js
src/invoices/InvoiceLineForm/InvoiceLineForm.js
src/invoices/InvoicesList/Invoice/InvoiceDetailsLayer.js
src/invoices/InvoicesList/InvoiceLine/InvoiceLineDetailsLayer.js
src/invoices/constants.js
test/bigtest/interactors/ConfirmationInteractor.js
test/bigtest/interactors/InvoiceDetails.js
test/bigtest/interactors/InvoiceLineDetailsInteractor.js
test/bigtest/network/configs/invoices.js
test/bigtest/network/configs/lines.js
test/bigtest/network/factories/line.js
test/bigtest/tests/InvoiceDetails/InvoiceDetails-test.js
test/bigtest/tests/InvoiceLine/invoice-line-details-test.js
test/bigtest/tests/InvoiceLine/invoice-line-edit-test.js
translations/ui-invoice/en.json

* Details screen of invoice line.
* Delete invoice and invoice line
https://issues.folio.org/browse/UINV-5 …

UINV-5 View invoice line details

---

src/invoices/InvoicesList/Invoice/InvoiceDetailsLayer.js
src/invoices/InvoicesList/Invoice/utils.js

https://issues.folio.org/browse/UINV-7
util to build invoice line based on POL
While it's …

UINV-7 add invoice lines bases on POL - correct field values

---

src/invoices/InvoiceForm/InvoiceForm.js

Voucher Information appearing on create/edit invoice form. It shouldn't.
https://issues.folio.org/browse/UINV-34 …

UINV-34 Voucher information accordion is not displayed

---

src/invoices/InvoiceLineForm/InvoiceLineForm.js
src/invoices/InvoicesList/InvoiceLine/InvoiceLineEditLayer.js

* when I edit subcription info I'm not able to save the line. Also when clicking "New" 
* disable edit of fields that shouldn't be edited on post-approval edit
https://issues.folio.org/browse/UINV-5
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …

UINV-5 fix button New, disable some fields

---

translations/ui-invoice/ar.json
translations/ui-invoice/ca.json
translations/ui-invoice/da.json
translations/ui-invoice/de.json
translations/ui-invoice/en_GB.json
translations/ui-invoice/en_SE.json
translations/ui-invoice/en_US.json
translations/ui-invoice/es.json
translations/ui-invoice/es_419.json
translations/ui-invoice/es_ES.json
translations/ui-invoice/fr.json
translations/ui-invoice/fr_FR.json
translations/ui-invoice/hu.json
translations/ui-invoice/it_IT.json
translations/ui-invoice/pt_BR.json
translations/ui-invoice/pt_PT.json
translations/ui-invoice/zh_CN.json

Update translation strings as of 20190709T154346

---

src/invoices/InvoicesList/InvoicesList.js

fix search index change
https://issues.folio.org/browse/UINV-26 …

UINV-26 fix search index change

---

package.json
test/bigtest/helpers/setup-application.js
test/bigtest/interactors/InvoiceFormInteractor.js
test/bigtest/network/config.js
test/bigtest/network/configs/units.js
test/bigtest/network/factories/unit.js
test/bigtest/network/models/unit.js
test/bigtest/network/serializers/unit.js
test/bigtest/tests/InvoiceEdit/invoice-create-test.js

Added missed filter mocks for Acquisition units, fixed test for Selecting Vendor of invoice. …

fix unit tests

---

src/common/components/ApprovedBy/ApprovedBy.js
src/common/components/ApprovedBy/index.js
src/common/constants/api.js
src/common/utils/getUserName.js
src/common/utils/index.js
src/invoices/InvoiceDetails/Information/Information.js
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoicesList/Invoice/InvoiceEditLayer.js
src/invoices/InvoicesList/InvoiceLine/InvoiceLineEditLayer.js

`approvedDate` and `approvalBy` cannot be set manually. 
Should be set by the system
https://issues.folio.org/browse/UINV-32 …

UINV-32 Invoice approval details set by system

---

translations/ui-invoice/ar.json

Update translation strings as of 20190718T013203

---

package.json

UINV-40 update interface

---

src/invoices/InvoiceDetails/Information/Information.js
test/bigtest/interactors/InvoiceDetails.js
test/bigtest/network/config.js
test/bigtest/network/configs/users.js
test/bigtest/network/factories/user.js
test/bigtest/network/models/user.js
test/bigtest/tests/InvoiceDetails/InvoiceDetails-test.js

https://issues.folio.org/browse/UINV-32
To cover new code by tests …

UINV-32 Add tests

---

src/common/resources/vendor.js
src/common/utils/getOptions.js
src/invoices/InvoiceLineForm/InvoiceLineForm.js
src/invoices/InvoicesList/Invoice/InvoiceDetailsLayer.js
src/invoices/InvoicesList/Invoice/utils.js
src/invoices/InvoicesList/InvoiceLine/InvoiceLineEditLayer.js
test/bigtest/interactors/InvoiceFormInteractor.js
test/bigtest/interactors/InvoiceLineFormInteractor.js
test/bigtest/interactors/OptionListInteractor.js
test/bigtest/network/configs/vendors.js
test/bigtest/tests/InvoiceDetails/InvoiceDetails-test.js
test/bigtest/tests/InvoiceLine/invoice-line-create-test.js
test/bigtest/tests/InvoiceLine/invoice-line-edit-test.js

The POL references an account number for the vendor that also references an accounting code. This information is critical for completing and paying invoices.
https://issues.folio.org/browse/UINV-36
For Invoice line the POL will possibly populate account number. If not the user can select from the Organizations erpCode and/or accounts[0].appSystemNo(s). For invoice line, accounting code and account number will NOT be required and accounting code will not be editable.
- Do JIRAs …

UINV-36 Populate invoice line "Account number" and "accounting code" based on POL details	

---

src/invoices/InvoiceDetails/Information/Information.js
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoicesList/Invoice/InvoiceDetailsLayer.js

https://issues.folio.org/browse/UINV-29
calculate total units from invoice lines quantity …

UINV-29 invoice details - total units

---

src/common/utils/getOptions.js
src/invoices/AdjustmentsForm/AdjustmentsForm.js
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoiceLineForm/InvoiceLineForm.js
src/invoices/InvoicesList/InvoiceLine/InvoiceLineEditLayer.js
src/invoices/InvoicesList/InvoicesList.js
src/settings/adjustments/SettingsAdjustmentsEditor/SettingsAdjustmentsEditor.js
translations/ui-invoice/en.json

Add adjustments to invoice line and invoice edit screens.
https://issues.folio.org/browse/UINV-8 …

UINV-8 use adjustment presets

---

translations/ui-invoice/pt_BR.json

Update translation strings as of 20190801T134041

---

src/invoices/InvoiceDetails/InvoiceLines/InvoiceLines.js

Invoice lines should be in numeric order on the Invoice Summary screen
https://issues.folio.org/browse/UINV-52 …

UINV-52 sort by invoice line number

---

src/invoices/AdjustmentsForm/AdjustmentsForm.js
src/invoices/InvoiceLineForm/InvoiceLineForm.js

https://issues.folio.org/browse/UINV-50
flag to manage adjs form on line form 
While it's …

UINV-50 User can 'pro rate' adjustment from invoice line

---

src/invoices/AdjustmentsDetails/AdjustmentsDetails.js
src/invoices/AdjustmentsDetails/index.js
src/invoices/InvoiceLineDetails/InvoiceLineDetails.js

Display Adjustments details in Invoice line details pane.
https://issues.folio.org/browse/UINV-8 …

UINV-8 Adjustments details

---

src/invoices/InvoicesList/invoicesListSearchConfig.js
translations/ui-invoice/en.json

User should be able to search for invoices by vendor accounting code
https://issues.folio.org/browse/UINV-43
Add accounting code option to search dropdown
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as …

UINV-43 Search by accounting code

---

src/settings/adjustments/SettingsAdjustmentsEditor/SettingsAdjustmentsEditor.js

https://issues.folio.org/browse/UINV-46 …

UINV-46 TECH-DEBT refactor styles in SettingsAdjustmentsEditor.js

---

src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLines.js
translations/ui-invoice/en.json

AdjustmentsTotal and Total should be displayed on the invoice view pane
https://issues.folio.org/browse/UINV-51
Add columns AdjustmentsTotal and Total with the symbol of invoice currency …

UINV-51 Display Adjustments and Total on invoice line

---

package.json
src/invoices/InvoiceDetails/Information/Information.js
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceForm/InvoiceForm.js

https://issues.folio.org/browse/UINV-23
use acq common components …

UINV-23 Ability to assign acquisition unit(s) to invoice records

---

translations/ui-invoice/ar.json
translations/ui-invoice/ca.json
translations/ui-invoice/da.json
translations/ui-invoice/de.json
translations/ui-invoice/en_GB.json
translations/ui-invoice/en_SE.json
translations/ui-invoice/en_US.json
translations/ui-invoice/es.json
translations/ui-invoice/es_419.json
translations/ui-invoice/es_ES.json
translations/ui-invoice/fr.json
translations/ui-invoice/fr_FR.json
translations/ui-invoice/hu.json
translations/ui-invoice/it_IT.json
translations/ui-invoice/pt_BR.json
translations/ui-invoice/pt_PT.json
translations/ui-invoice/zh_CN.json

Update translation strings as of 20190815T130307

---

src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoicesList/Invoice/InvoiceDetailsLayer.js
src/invoices/InvoicesList/InvoicesList.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-37
`withTags` usage
While it's helpful for reviewers to …

UINV-37 Assign tags to Invoice Records

---

translations/ui-invoice/ar.json
translations/ui-invoice/ca.json
translations/ui-invoice/da.json
translations/ui-invoice/de.json
translations/ui-invoice/en_GB.json
translations/ui-invoice/en_SE.json
translations/ui-invoice/en_US.json
translations/ui-invoice/es.json
translations/ui-invoice/es_419.json
translations/ui-invoice/es_ES.json
translations/ui-invoice/fr.json
translations/ui-invoice/fr_FR.json
translations/ui-invoice/hu.json
translations/ui-invoice/it_IT.json
translations/ui-invoice/pt_BR.json
translations/ui-invoice/pt_PT.json
translations/ui-invoice/zh_CN.json

Update translation strings as of 20190819T080537

---

src/common/constants/api.js
src/common/resources/invoice.js
src/invoices/InvoiceDocument/InvoiceDocument.css
src/invoices/InvoiceDocument/InvoiceDocument.js
src/invoices/InvoiceDocument/InvoiceDocumentContainer.js
src/invoices/InvoiceDocument/index.js
src/invoices/InvoiceForm/InvoiceDocumentsForm/InvoiceDocumentFields/InvoiceDocumentFields.css
src/invoices/InvoiceForm/InvoiceDocumentsForm/InvoiceDocumentFields/InvoiceDocumentFields.js
src/invoices/InvoiceForm/InvoiceDocumentsForm/InvoiceDocumentFields/index.js
src/invoices/InvoiceForm/InvoiceDocumentsForm/InvoiceDocumentsForm.js
src/invoices/InvoiceForm/InvoiceDocumentsForm/index.js
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoiceForm/InvoiceLinksForm/InvoiceLinksForm.js
src/invoices/InvoiceForm/InvoiceLinksForm/index.js
src/invoices/InvoicesList/Invoice/InvoiceEditLayer.js
src/invoices/InvoicesList/InvoicesList.js
src/invoices/InvoicesList/utils.js
test/bigtest/network/config.js
test/bigtest/network/configs/documents.js
test/bigtest/network/factories/document.js
test/bigtest/network/models/document.js
test/bigtest/network/models/invoice0.js
test/bigtest/network/serializers/document.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-15
* tests
* error handling …

UINV-15 Create and save invoice details - Links section

---

src/invoices/AdjustmentsDetails/AdjustmentsDetails.js
src/invoices/AdjustmentsForm/AdjustmentsForm.js
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLines.js
test/bigtest/interactors/ButtonInteractor.js
test/bigtest/interactors/InvoiceDetails.js
test/bigtest/interactors/InvoiceLineDetailsInteractor.js
test/bigtest/interactors/InvoiceLineFormInteractor.js
test/bigtest/interactors/SelectInteractor.js
test/bigtest/interactors/TextFieldInteractor.js
test/bigtest/interactors/index.js
test/bigtest/network/configs/lines.js
test/bigtest/tests/InvoiceLine/invoice-line-edit-test.js

tests for adding adjustments to invoice lines
https://issues.folio.org/browse/UINV-48
While …

UINV-48 tests invoice line adjustments add

---

src/invoices/InvoiceDetails/Information/Information.js
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoicesList/InvoicesList.js

Update invoice subtotal, adjustments and total amounts to display in correct format based on currency and localization
https://issues.folio.org/browse/UINV-54
Use `<AmountWithCurrencyField />` from `@folio/stripes-acq-components` for subtotal, adjustments, total amounts 
Ideally all of the PRs involved in breaking changes would be merged in the same day to …

UINV-54 Invoice number formating

---

src/common/resources/voucher.js
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceDetails/VoucherInformation/VoucherInformation.js
src/invoices/InvoiceDetails/VoucherInformation/VoucherInformationContainer.js
src/invoices/InvoicesList/Invoice/Invoice.js
src/invoices/Voucher/Voucher.js
src/invoices/Voucher/VoucherDetails.js
src/invoices/Voucher/VoucherLinesDetails.js
src/invoices/Voucher/VoucherView.js
src/invoices/Voucher/VoucherViewLayer.js
src/invoices/Voucher/utils.js
src/invoices/constants.js
test/bigtest/interactors/InvoiceDetails.js
test/bigtest/interactors/VoucherView.js
test/bigtest/tests/InvoiceDetails/voucherInformation-test.js
translations/ui-invoice/en.json

Create Voucher View page
https://issues.folio.org/browse/UINV-13 …

UINV-13 View voucher from invoice

---

src/common/constants/constants.js
src/common/resources/voucher.js
src/settings/VoucherNumber/SettingsVoucherNumber.js
src/settings/VoucherNumber/SettingsVoucherNumberForm.js
src/settings/VoucherNumber/SettingsVoucherNumberReset.js
test/bigtest/interactors/SettingsVoucherNumberInteractor.js
test/bigtest/network/configs/settingVoucherNumber.js
test/bigtest/tests/settings/setting-voucher-number-test.js
translations/ui-invoice/en.json

this will accommodate other electronic documentation numbers.
https://issues.folio.org/browse/UINV-9
Implement logic to allow changing the starting number.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as …

UINV-9 Setting: voucherNumber is editable (Boolean) and Add prefix to voucher number

---

src/invoices/InvoiceDetails/DocumentsDetails/DocumentsDetails.js
src/invoices/InvoiceDetails/DocumentsDetails/DocumentsDetailsContainer.js
src/invoices/InvoiceDetails/DocumentsDetails/index.js
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/constants.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-15 …

UINV-15 invoice documents base view

---

src/common/constants/api.js
src/common/constants/constants.js
src/common/resources/configTags.js
src/common/resources/index.js
src/common/resources/tags.js
src/invoices/InvoiceLineDetails/InvoiceLineDetails.js
src/invoices/InvoicesList/InvoiceLine/InvoiceLineDetailsLayer.js
src/invoices/Tags/TagsBadge/TagsBadge.js
src/invoices/Tags/TagsBadge/TagsBadgeContainer.js
src/invoices/Tags/TagsBadge/index.js
src/invoices/Tags/TagsContainer.js
src/invoices/Tags/TagsForm.js
src/invoices/Tags/index.js
test/bigtest/interactors/InvoiceLineDetailsInteractor.js
test/bigtest/interactors/InvoiceLineDetailsTags.js
test/bigtest/tests/InvoiceLine/invoice-line-tags-test.js
translations/ui-invoice/en.json

To display, assign, unassign, and output tags associated with individual INVOICE LINE records within the FOLIO Invoice app
https://issues.folio.org/browse/UINV-38
Write tests
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …

UINV-38 Assign tags to Invoice Line Records

---

src/invoices/Tags/TagsForm.js

Exclude the ability to add an empty tag
https://issues.folio.org/browse/UINV-38
While it's …

UINV-38 Fix adding empty tag

---

src/index.js
src/invoices/InvoiceDetails/InvoiceActions/ApproveInvoiceAction/ApproveInvoiceAction.css
src/invoices/InvoiceDetails/InvoiceActions/ApproveInvoiceAction/ApproveInvoiceAction.js
src/invoices/InvoiceDetails/InvoiceActions/ApproveInvoiceAction/ApproveInvoiceActionContainer.js
src/invoices/InvoiceDetails/InvoiceActions/ApproveInvoiceAction/index.js
src/invoices/InvoiceDetails/InvoiceActions/index.js
src/invoices/InvoiceDetails/InvoiceDetails.js
test/bigtest/interactors/InvoiceDetails.js
test/bigtest/tests/InvoiceDetails/InvoiceDetailsApprove-test.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-62
new component wit custom hooks usage
While it's …

UINV-62 Require invoice approval to 'pay' invoice

---

package.json
src/invoices/InvoiceDetails/InvoiceActions/PayInvoiceAction/PayInvoiceAction.js
src/invoices/InvoiceDetails/InvoiceActions/PayInvoiceAction/PayInvoiceActionContainer.js

https://issues.folio.org/browse/UINV-63
https://issues.folio.org/browse/UINV-62
While it's …

UINV-62 UINV-63 review fixes

---

translations/ui-invoice/ar.json
translations/ui-invoice/ca.json
translations/ui-invoice/da.json
translations/ui-invoice/de.json
translations/ui-invoice/en_GB.json
translations/ui-invoice/en_SE.json
translations/ui-invoice/en_US.json
translations/ui-invoice/es.json
translations/ui-invoice/es_419.json
translations/ui-invoice/es_ES.json
translations/ui-invoice/fr.json
translations/ui-invoice/fr_FR.json
translations/ui-invoice/hu.json
translations/ui-invoice/it_IT.json
translations/ui-invoice/pt_BR.json
translations/ui-invoice/pt_PT.json
translations/ui-invoice/zh_CN.json

Update translation strings as of 20190903T134424

---

src/invoices/InvoiceLineForm/InvoiceLineForm.js
src/invoices/InvoicesList/InvoiceLine/InvoiceLineEditLayer.js

https://issues.folio.org/browse/UINV-57
fix condition for disable …

UINV-57 update condition for disable fund distributions fields

---

src/invoices/InvoicesList/InvoiceLine/InvoiceLineEditLayer.js

https://issues.folio.org/browse/UINV-67
Remove hardcoded fund  …

UINV-67 Remove hardcoded fund code/encumbranceId from new invoiceLine fundDistros

---

package.json
src/invoices/InvoiceDetails/InvoiceLines/AddInvoiceLinesAction.js
src/invoices/InvoicesList/invoicesListSearchConfig.js

To fix search query with `Keyword` option.
https://issues.folio.org/browse/UIOR-367
The search query is failing due to incorrect format of `queryTemplate`. So to fix this we use a common function to generate queryTemplate. …

UIOR-367 fix search query

---

src/invoices/AdjustmentsDetails/AdjustmentsDetails.js
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLines.js
src/invoices/InvoiceDetails/VoucherInformation/VoucherInformation.js
src/invoices/InvoicesList/InvoicesList.js
src/invoices/Voucher/VoucherLinesDetails.js

ACQ Apps: MCL column width updates
https://issues.folio.org/browse/STCOM-590
Remove `columnWidths` prop from MCL …

STCOM-590 ACQ Apps: MCL column width updates

---

src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceDetails/InvoiceLines/AddInvoiceLinesAction.js
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLinesActions.js

https://issues.folio.org/browse/UINV-42 …

UINV-42 Shouldn't be allowed to add invoiceLines to an approved invoice

---

src/common/utils/getApproveErrorMessage.js
src/common/utils/index.js
src/invoices/InvoiceDetails/InvoiceActions/ApproveInvoiceAction/ApproveInvoiceAction.js
test/bigtest/tests/InvoiceDetails/InvoiceDetailsApprove-test.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-65
Show error message
While it's helpful for reviewers …

UINV-65 show error message

---

src/invoices/InvoiceDetails/InvoiceLines/AddInvoiceLinesAction.js
src/invoices/InvoiceDetails/VoucherInformation/VoucherInformationContainer.js
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoiceLineForm/InvoiceLineForm.js
src/invoices/InvoicesList/Invoice/Invoice.js
src/invoices/InvoicesList/Invoice/InvoiceDetailsLayer.js

* remove warnings agains Select fields;
* remove errors if no voucher(sample data);
* make InvoiceDetailsLayer a functional component; …

Refactorings to invoice

---

translations/ui-invoice/ar.json

Update translation strings as of 20191004T135530

---

package.json

Bump up okapi interfaces

---

src/invoices/InvoiceLineForm/InvoiceLineForm.js
src/invoices/InvoiceLineForm/validate.js
test/bigtest/network/factories/line.js

support changes in fund distribution
https://issues.folio.org/browse/UINV-68
While it's …

Uinv 68 add type to fund distribution

---

src/invoices/InvoiceLineForm/validate.js

Support validation of 100% distributed amount
https://issues.folio.org/browse/UINV-68
While …

UINV-68 fix validation

---

src/invoices/AdjustmentsForm/AdjustmentsForm.js
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoiceForm/validate.js
test/bigtest/network/factories/line.js
test/bigtest/tests/InvoiceEdit/InvoiceEdit-test.js
test/bigtest/tests/InvoiceLine/invoice-line-edit-test.js
translations/ui-invoice/en.json

Add ability to specify fund distro for non-prorated invoice adjustments
https://issues.folio.org/browse/UINV-71 …

UINV-71 fund distribution for non-prorated adjustments

---

src/index.js
src/invoices/InvoiceDetails/DocumentsDetails/DocumentsDetailsContainer.js
src/invoices/InvoiceDetails/InvoiceActions/ApproveInvoiceAction/ApproveInvoiceActionContainer.js
src/invoices/InvoiceDetails/InvoiceActions/PayInvoiceAction/PayInvoiceActionContainer.js
src/invoices/InvoiceDocument/InvoiceDocumentContainer.js
src/invoices/InvoicesList/Invoice/Invoice.js
src/invoices/InvoicesList/InvoiceLine/InvoiceLine.js
src/invoices/Voucher/Voucher.js
src/settings/adjustments/SettingsAdjustments.js

fix router improts

---

src/invoices/AdjustmentsForm/AdjustmentsForm.js
src/invoices/InvoiceForm/InvoiceForm.js

* hide fund distr if relation to total = included in;
* how checkboxes with labes vertically;
* show currency from invoice;
https://issues.folio.org/browse/UINV-71
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …

UINV-71 hide fund distribution

---

src/invoices/AdjustmentsForm/AdjustmentsForm.js
src/invoices/InvoiceForm/InvoiceForm.js

Add ability to provide fund distributions to adjustment even if its type is Persentage
https://issues.folio.org/browse/UINV-71 …

UINV-72 calculate fund distr for percentage adjustment

---

src/invoices/AdjustmentsForm/AdjustmentsForm.js

Fix NaN if there was no value input in adjustment amount field.
https://issues.folio.org/browse/UINV-71 …

UINV-71 fix NaN

---

translations/ui-invoice/ar.json
translations/ui-invoice/ca.json
translations/ui-invoice/da.json
translations/ui-invoice/de.json
translations/ui-invoice/en_GB.json
translations/ui-invoice/en_SE.json
translations/ui-invoice/en_US.json
translations/ui-invoice/es.json
translations/ui-invoice/es_419.json
translations/ui-invoice/es_ES.json
translations/ui-invoice/fr.json
translations/ui-invoice/fr_FR.json
translations/ui-invoice/hu.json
translations/ui-invoice/it_IT.json
translations/ui-invoice/pt_BR.json
translations/ui-invoice/pt_PT.json
translations/ui-invoice/ru.json
translations/ui-invoice/zh_CN.json
translations/ui-invoice/zh_TW.json

Update translation strings as of 20191022T162142

---

src/invoices/AdjustmentsDetails/AdjustmentsDetails.js
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceLineDetails/InvoiceLineDetails.js
src/invoices/InvoiceLineDetails/InvoiceLineInformation.js
src/invoices/InvoicesList/InvoiceLine/InvoiceLineDetailsLayer.js

The adjustments accordion on both invoice details and invoice-line details panes makes it impossible to determine if a given adjustment is an amount or percentage.
Add Percent or Currency signs for Amount
https://issues.folio.org/browse/UINV-76
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …

UINV-76 Cannot distinguish between percent and amount adjustments

---

src/common/utils/calculateTotalAmount.js
src/invoices/AdjustmentsForm/AdjustmentsForm.js
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceForm/validate.js
src/invoices/constants.js

Update view for Fund distribution information on Invoice and invoice line
https://issues.folio.org/browse/UINV-80 …

UINV-80 update fund distr view and fix validation for percent

---

src/common/components/FormFooter/FormFooter.js
src/common/components/FormFooter/index.js
src/common/components/index.js
src/common/utils/index.js
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoiceLineForm/InvoiceLineForm.js
test/bigtest/interactors/InvoiceFormInteractor.js
test/bigtest/interactors/InvoiceLineFormInteractor.js
test/bigtest/interactors/common/FormFooter.js
test/bigtest/tests/InvoiceCreate/InvoiceCreate-test.js
test/bigtest/tests/InvoiceCreate/InvoiceCreateDocuments-test.js
test/bigtest/tests/InvoiceEdit/InvoiceEdit-test.js
test/bigtest/tests/InvoiceEdit/InvoiceEditDocuments-test.js
test/bigtest/tests/InvoiceLine/invoice-line-create-test.js
test/bigtest/tests/InvoiceLine/invoice-line-edit-test.js
translations/ui-invoice/en.json

FOLIO is adopting a floating menu bar for the "Save and close" and "Cancel" operations
https://issues.folio.org/browse/UINV-78 …

UINV-78 Invoices - update save and close buttons

---

translations/ui-invoice/ar.json
translations/ui-invoice/ca.json
translations/ui-invoice/da.json
translations/ui-invoice/de.json
translations/ui-invoice/en_GB.json
translations/ui-invoice/en_SE.json
translations/ui-invoice/en_US.json
translations/ui-invoice/es.json
translations/ui-invoice/es_419.json
translations/ui-invoice/es_ES.json
translations/ui-invoice/fr.json
translations/ui-invoice/fr_FR.json
translations/ui-invoice/hu.json
translations/ui-invoice/it_IT.json
translations/ui-invoice/ja.json
translations/ui-invoice/pt_BR.json
translations/ui-invoice/pt_PT.json
translations/ui-invoice/ru.json
translations/ui-invoice/zh_CN.json
translations/ui-invoice/zh_TW.json

Update translation strings as of 20191101T131808

---

translations/ui-invoice/pt_BR.json

Update translation strings as of 20191101T174958

---

src/invoices/AdjustmentsForm/AdjustmentsForm.js

Fix to change the type of adjustment from the first click
While it's helpful for reviewers …

Sometimes you need to click twice to change the type

---

translations/ui-invoice/ar.json
translations/ui-invoice/es_ES.json
translations/ui-invoice/pt_BR.json
translations/ui-invoice/ru.json

Update translation strings as of 20191104T173556

---

src/invoices/InvoicesList/InvoicesListFilters.js
src/invoices/InvoicesList/constants.js
src/invoices/InvoicesList/invoicesListFilterConfig.js
test/bigtest/interactors/InvoiceLineDetailsTags.js

https://issues.folio.org/browse/UINV-81 …

UINV-81 Filter invoices by tags

---

translations/ui-invoice/ar.json
translations/ui-invoice/ca.json
translations/ui-invoice/da.json
translations/ui-invoice/de.json
translations/ui-invoice/en_GB.json
translations/ui-invoice/en_SE.json
translations/ui-invoice/en_US.json
translations/ui-invoice/es.json
translations/ui-invoice/es_419.json
translations/ui-invoice/es_ES.json
translations/ui-invoice/fr.json
translations/ui-invoice/fr_FR.json
translations/ui-invoice/hu.json
translations/ui-invoice/it_IT.json
translations/ui-invoice/ja.json
translations/ui-invoice/pt_BR.json
translations/ui-invoice/pt_PT.json
translations/ui-invoice/ru.json
translations/ui-invoice/zh_CN.json
translations/ui-invoice/zh_TW.json

Update translation strings as of 20191112T144117

---

package.json
src/common/resources/invoice.js
src/invoices/InvoiceDocument/InvoiceDocumentContainer.js
src/invoices/InvoicesList/Invoice/InvoiceEditLayer.js
src/invoices/InvoicesList/InvoicesList.js
test/bigtest/tests/InvoiceEdit/InvoiceEdit-test.js
test/bigtest/tests/InvoiceEdit/InvoiceEditDocuments-test.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-2 …

UINV-2 Duplication checking for vendor invoice number

---

src/invoices/InvoicesList/Invoice/InvoiceEditLayer.js

fix code smell

---

translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-89 …

UINV-89 Settings: Spelling mistake

---

translations/ui-invoice/pt_BR.json

Update translation strings as of 20191122T191330

---

src/common/utils/getApproveErrorMessage.js
src/invoices/InvoiceDetails/InvoiceActions/PayInvoiceAction/PayInvoiceAction.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-83 …

UINV-83 Prevent paying with Funds that have insufficient amounts to cover distribution

---

package.json
src/common/constants/constants.js
src/common/utils/invoiceUtils.js

Make dates consistent
https://issues.folio.org/browse/UINV-88 …

UINV-88 make dates consistent

---

.eslintrc
CHANGELOG.md
PULL_REQUEST_TEMPLATE.md
package.json
src/invoices/InvoicesList/Invoice/InvoiceEditLayer.js

https://issues.folio.org/browse/UINV-86 …

Release v1.2.0

---

CHANGELOG.md
src/common/resources/configAddress.js

https://issues.folio.org/browse/UINV-93 …

UINV-93 Address lookup not working in Invoices

---

src/common/utils/index.js
src/common/utils/validators.js
src/invoices/AdjustmentsForm/AdjustmentsForm.js
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoiceLineForm/InvoiceLineForm.js
src/settings/adjustments/SettingsAdjustmentsEditor/SettingsAdjustmentsEditor.js
translations/ui-invoice/en.json

Validation from stripes-acq-components usage
https://issues.folio.org/browse/UINV-94
While …

UINV-94 Validation from stripes-acq-components usage

---

CHANGELOG.md
src/common/constants/constants.js
src/settings/adjustments/SettingsAdjustmentsEditor/SettingsAdjustmentsEditorContainer.js

https://issues.folio.org/browse/UINV-96 …

UINV-96 Can not create pre-set adjustments

---

CHANGELOG.md
src/common/utils/calculateTotalAmount.js
src/invoices/AdjustmentsForm/AdjustmentsForm.js
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceForm/validate.js
src/invoices/InvoiceLineForm/InvoiceLineForm.js
src/invoices/InvoiceLineForm/validate.js
src/invoices/InvoicesList/Invoice/InvoiceDetailsLayer.js

For proper calculations of Fund distribution amounts we have to use common calculation functions from stripes-acq-components
https://issues.folio.org/browse/UIOR-464
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …

UIOR-464 pass stripes and currency to money calculations

---

CHANGELOG.md
PULL_REQUEST_TEMPLATE.md
package.json

https://issues.folio.org/browse/UINV-95 …

Release v1.2.1

---

translations/ui-invoice/es.json
translations/ui-invoice/es_419.json
translations/ui-invoice/es_ES.json

Update translation strings as of 20191223T213508

---

CHANGELOG.md
src/invoices/InvoiceForm/InvoiceDocumentsForm/InvoiceDocumentsForm.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-109 …

UINV-109 Limit document size

---

src/invoices/InvoiceForm/InvoiceDocumentsForm/InvoiceDocumentsForm.js

https://issues.folio.org/browse/UINV-109 …

UINV-109 change file size restriction from 2MB to 20MB

---

package.json

https://issues.folio.org/browse/MODORDERS-354 …

MODORDERS-354 new okapi interfaces

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/UINV-107 …

UINV-107 Update settings permission label

---

CHANGELOG.md
src/invoices/InvoicesList/Invoice/utils.js
test/bigtest/tests/InvoiceLine/invoice-line-edit-test.js

https://issues.folio.org/browse/UIOR-239 …

UIOR-239 Use titleOrPackage instead of title

---

CHANGELOG.md
src/invoices/InvoicesList/Invoice/utils.js

https://issues.folio.org/browse/UINV-114 …

UINV-114 Invoice line not retrieving Total estimated price when linking POL

---

package.json
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceLineDetails/InvoiceLineDetails.js
test/bigtest/index.js
test/bigtest/network/config.js
test/bigtest/network/factories/invoice.js

* button Actions returned to the Invoice Line details;
* we need to memoize fund distributions so FundDistView doesn't fetch funds and transactions on every render;
* so InvoiceDetails component was rewritten to use hooks;
Basically, the first tag element of the any additional action in the Pane header now should be the `PaneMenu`. And since TagsBadge was wrapped in `stripesCOnnect()` - it was broken and no Actions were displayed. …

fix tests and Actions button on Invoice Line details

---

CHANGELOG.md
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoiceLineDetails/InvoiceLineDetails.js
src/invoices/InvoiceLineForm/InvoiceLineForm.js

Save and close and cancel bar not fixed to bottom of form
https://issues.folio.org/browse/UINV-105 …

UINV-105 fix footer height

---

CHANGELOG.md
src/settings/BatchGroupConfigurationSettings/BatchGroupConfigurationSettings.js
src/settings/BatchGroupConfigurationSettings/index.js
src/settings/BatchGroupsSettings/BatchGroupsSettings.js
src/settings/BatchGroupsSettings/index.js
src/settings/InvoiceSettings.js
test/bigtest/interactors/BatchGroupConfigurationSettingsInteractor.js
test/bigtest/interactors/BatchGroupsSettingsInteractor.js
test/bigtest/tests/settings/batch-group-configuration-settings-test.js
test/bigtest/tests/settings/batch-groups-settings-test.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-100 …

UINV-100 Settings: Add Batch group and Batch group settings subheadings to invoice settings

---

translations/ui-invoice/ar.json
translations/ui-invoice/ca.json
translations/ui-invoice/da.json
translations/ui-invoice/de.json
translations/ui-invoice/en_GB.json
translations/ui-invoice/en_SE.json
translations/ui-invoice/en_US.json
translations/ui-invoice/es.json
translations/ui-invoice/es_419.json
translations/ui-invoice/es_ES.json
translations/ui-invoice/fr.json
translations/ui-invoice/fr_FR.json
translations/ui-invoice/he.json
translations/ui-invoice/hu.json
translations/ui-invoice/it_IT.json
translations/ui-invoice/ja.json
translations/ui-invoice/pt_BR.json
translations/ui-invoice/pt_PT.json
translations/ui-invoice/ru.json
translations/ui-invoice/ur.json
translations/ui-invoice/zh_CN.json
translations/ui-invoice/zh_TW.json

Update translation strings as of 20200211T224145

---

translations/ui-invoice/ar.json
translations/ui-invoice/ca.json
translations/ui-invoice/da.json
translations/ui-invoice/de.json
translations/ui-invoice/en_GB.json
translations/ui-invoice/en_SE.json
translations/ui-invoice/en_US.json
translations/ui-invoice/es.json
translations/ui-invoice/es_419.json
translations/ui-invoice/es_ES.json
translations/ui-invoice/fr.json
translations/ui-invoice/fr_FR.json
translations/ui-invoice/he.json
translations/ui-invoice/hu.json
translations/ui-invoice/it_IT.json
translations/ui-invoice/ja.json
translations/ui-invoice/pt_BR.json
translations/ui-invoice/pt_PT.json
translations/ui-invoice/ru.json
translations/ui-invoice/ur.json
translations/ui-invoice/zh_CN.json
translations/ui-invoice/zh_TW.json

Update translation strings as of 20200217T172736

---

CHANGELOG.md
package.json
src/common/constants/api.js
src/settings/BatchGroupsSettings/BatchGroupsSettings.js
test/bigtest/interactors/BatchGroupsSettingsInteractor.js
test/bigtest/network/config.js
test/bigtest/network/configs/batchgroup.js
test/bigtest/network/factories/batchgroup.js
test/bigtest/network/models/batchgroup.js
test/bigtest/network/serializers/batchgroup.js
test/bigtest/tests/settings/batch-groups-settings-test.js
translations/ui-invoice/en.json

Invoice settings: Batch groups
https://issues.folio.org/browse/UINV-111
While it's helpful …

UINV-111 Invoice settings: Batch groups

---

src/invoices/InvoiceDetails/InvoiceActions/InvoiceActions.js
src/invoices/InvoiceLineDetails/ActionMenu.js

https://issues.folio.org/browse/UINV-119 …

UINV-119 move Delete button to the bottom

---

src/settings/BatchGroupsSettings/BatchGroupsSettings.js

https://issues.folio.org/browse/UINV-111 …

UINV-111 remove metadata before save so system groups are editable

---

translations/ui-invoice/ar.json
translations/ui-invoice/ca.json
translations/ui-invoice/da.json
translations/ui-invoice/de.json
translations/ui-invoice/en_GB.json
translations/ui-invoice/en_SE.json
translations/ui-invoice/en_US.json
translations/ui-invoice/es.json
translations/ui-invoice/es_419.json
translations/ui-invoice/es_ES.json
translations/ui-invoice/fr.json
translations/ui-invoice/fr_FR.json
translations/ui-invoice/he.json
translations/ui-invoice/hu.json
translations/ui-invoice/it_IT.json
translations/ui-invoice/ja.json
translations/ui-invoice/pt_BR.json
translations/ui-invoice/pt_PT.json
translations/ui-invoice/ru.json
translations/ui-invoice/ur.json
translations/ui-invoice/zh_CN.json
translations/ui-invoice/zh_TW.json

Update translation strings as of 20200220T141728

---

CHANGELOG.md
package.json
src/common/resources/batchGroups.js
src/common/resources/index.js
src/settings/BatchGroupConfigurationSettings/BatchGroupConfigurationFormFooter.js
src/settings/BatchGroupConfigurationSettings/BatchGroupConfigurationSettings.js
src/settings/BatchGroupConfigurationSettings/BatchGroupCongiurationForm.js
src/settings/BatchGroupConfigurationSettings/BatchGroupsField.js
test/bigtest/interactors/BatchGroupConfigurationSettingsInteractor.js
test/bigtest/tests/settings/batch-group-configuration-settings-test.js
translations/ui-invoice/en.json

Create settings form for Batch group settings (Multiple Batch groups)
https://issues.folio.org/browse/UINV-101 …

UINV-101 Create settings form for Batch group settings (Multiple Batch groups)

---

src/settings/BatchGroupConfigurationSettings/BatchGroupConfigurationSettings.js

Fix BatchGroupId - add if condition to prevent `undefined` for initial rendering
While it's …

UINV-103 Fix BatchGroupId

---

src/settings/BatchGroupConfigurationSettings/BatchGroupCongiurationForm.js
src/settings/BatchGroupConfigurationSettings/TogglePassword.js

UINV-103 Add styles for creds button

---

src/common/constants/constants.js
src/common/utils/getOptions.js
src/invoices/InvoiceDetails/InvoiceDetailsContainer.js
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoiceForm/InvoiceFormContainer.js
src/invoices/InvoiceLineDetails/InvoiceLineDetailsContainer.js
src/invoices/InvoicesList/InvoicesListContainer.js
test/bigtest/interactors/InvoiceFormInteractor.js
test/bigtest/tests/InvoiceCreate/InvoiceCreate-test.js
test/bigtest/tests/InvoiceCreate/InvoiceCreateDocuments-test.js

https://issues.folio.org/browse/UINV-124 …

UINV-124 Invoices - Replace org selection components with organization lookup

---

translations/ui-invoice/pt_BR.json

Update translation strings as of 20200314T132532

---

translations/ui-invoice/fr_FR.json

Update translation strings as of 20200316T134017

---

src/invoices/InvoiceDetails/InvoiceDetailsContainer.js

fix approve and pay is breaking app

---

translations/ui-invoice/ar.json
translations/ui-invoice/ca.json
translations/ui-invoice/da.json
translations/ui-invoice/de.json
translations/ui-invoice/en_GB.json
translations/ui-invoice/en_SE.json
translations/ui-invoice/en_US.json
translations/ui-invoice/es.json
translations/ui-invoice/es_419.json
translations/ui-invoice/es_ES.json
translations/ui-invoice/fr.json
translations/ui-invoice/fr_FR.json
translations/ui-invoice/he.json
translations/ui-invoice/hu.json
translations/ui-invoice/it_IT.json
translations/ui-invoice/ja.json
translations/ui-invoice/pt_BR.json
translations/ui-invoice/pt_PT.json
translations/ui-invoice/ru.json
translations/ui-invoice/ur.json
translations/ui-invoice/zh_CN.json
translations/ui-invoice/zh_TW.json

Update translation strings as of 20200319T202257

---

src/common/resources/batchVoucherExportsResource.js
src/settings/BatchGroupConfigurationSettings/BatchGroupConfigurationForm.js
src/settings/BatchGroupConfigurationSettings/BatchGroupConfigurationFormFooter.js
src/settings/BatchGroupConfigurationSettings/BatchGroupConfigurationSettings.js
src/settings/BatchGroupConfigurationSettings/BatchVoucherExportsList/BatchVoucherExportsListContainer.js
src/settings/BatchGroupConfigurationSettings/utils.js

for test purposes we can create voucher exports by hitting Run manual export button
While …

UINV-106 generate voucher exports for testing story

---

translations/ui-invoice/ar.json
translations/ui-invoice/fr_FR.json

Update translation strings as of 20200323T195201

---

src/common/utils/getApproveErrorMessage.js
src/invoices/InvoiceDetails/InvoiceDetailsContainer.js

fix refresh of invoice

---

translations/ui-invoice/ru.json

Update translation strings as of 20200325T162106

---

CHANGELOG.md
package.json
src/invoices/InvoiceDetails/InvoiceDetailsContainer.js
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoiceForm/InvoiceFormContainer.js
src/settings/BatchGroupConfigurationSettings/BatchGroupConfigurationFormFooter.js

Release and removed some console warnings
https://issues.folio.org/browse/UINV-132
While …

Release v2.0.1

---

CHANGELOG.md
package.json

Backport of release v2.0.2

---

translations/ui-invoice/ar.json
translations/ui-invoice/ca.json
translations/ui-invoice/da.json
translations/ui-invoice/de.json
translations/ui-invoice/en_GB.json
translations/ui-invoice/en_SE.json
translations/ui-invoice/en_US.json
translations/ui-invoice/es.json
translations/ui-invoice/es_419.json
translations/ui-invoice/es_ES.json
translations/ui-invoice/fr.json
translations/ui-invoice/fr_FR.json
translations/ui-invoice/he.json
translations/ui-invoice/hu.json
translations/ui-invoice/it_IT.json
translations/ui-invoice/ja.json
translations/ui-invoice/pt_BR.json
translations/ui-invoice/pt_PT.json
translations/ui-invoice/ru.json
translations/ui-invoice/ur.json
translations/ui-invoice/zh_CN.json
translations/ui-invoice/zh_TW.json

Update translation strings as of 20200403T124750

---

CHANGELOG.md
src/invoices/AdjustmentsForm/AdjustmentsForm.js
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoiceLineForm/InvoiceLineForm.js
src/invoices/Voucher/VoucherEditForm/VoucherEditForm.js
src/settings/BatchGroupConfigurationSettings/BatchGroupConfigurationForm.js
src/settings/BatchGroupConfigurationSettings/TogglePassword.js
src/settings/VoucherNumber/SettingsVoucherNumberForm.js
src/settings/VoucherNumber/SettingsVoucherNumberReset.js

Accessibility Error: Form elements must have labels
https://issues.folio.org/browse/UINV-127 …

UINV-127 Accessibility Error: Form elements must have labels

---

translations/ui-invoice/ar.json
translations/ui-invoice/ru.json

Update translation strings as of 20200406T162815

---

src/settings/BatchGroupConfigurationSettings/BatchVoucherExportsList.js

we need to show end of list marker
https://github.com/folio-org/stripes-components/blob/master/lib/MultiColumnList/MCLRenderer.js#L940
`visible={virtualize && (dataEndReached || (totalCount > 0 && totalCount <= renderPosition))}`
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …

show End of List marker

---

CHANGELOG.md
src/common/resources/batchGroups.js
src/common/utils/getOptions.js
src/invoices/InvoiceDetails/BatchGroupValue/BatchGroupValue.js
src/invoices/InvoiceDetails/BatchGroupValue/index.js
src/invoices/InvoiceDetails/Information/Information.js
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceDetails/InvoiceDetailsContainer.js
src/invoices/InvoiceForm/FieldBatchGroup/FieldBatchGroup.js
src/invoices/InvoiceForm/FieldBatchGroup/index.js
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoiceForm/InvoiceFormContainer.js
src/settings/BatchGroupConfigurationSettings/BatchGroupsField.js
test/bigtest/network/factories/invoice.js
test/bigtest/tests/InvoiceCreate/InvoiceCreate-test.js
test/bigtest/tests/InvoiceCreate/InvoiceCreateDocuments-test.js
test/bigtest/tests/InvoiceDetails/InvoiceDetailsApprove-test.js
test/bigtest/tests/InvoiceDetails/InvoiceDetailsPay-test.js
test/bigtest/tests/InvoiceEdit/InvoiceEdit-test.js
test/bigtest/tests/InvoiceLine/invoice-line-edit-test.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-130 …

UINV-130 Add batch group to invoice

---

src/invoices/InvoiceForm/InvoiceForm.js

The initial status of accordions in Invoice Form:
- invoice information - open
- voucher information - closed …

Fix initial status of Information accordion

---

translations/ui-invoice/ar.json
translations/ui-invoice/ca.json
translations/ui-invoice/da.json
translations/ui-invoice/de.json
translations/ui-invoice/en_GB.json
translations/ui-invoice/en_SE.json
translations/ui-invoice/en_US.json
translations/ui-invoice/es.json
translations/ui-invoice/es_419.json
translations/ui-invoice/es_ES.json
translations/ui-invoice/fr.json
translations/ui-invoice/fr_FR.json
translations/ui-invoice/he.json
translations/ui-invoice/hu.json
translations/ui-invoice/it_IT.json
translations/ui-invoice/ja.json
translations/ui-invoice/pt_BR.json
translations/ui-invoice/pt_PT.json
translations/ui-invoice/ru.json
translations/ui-invoice/ur.json
translations/ui-invoice/zh_CN.json
translations/ui-invoice/zh_TW.json

Update translation strings as of 20200409T134057

---

CHANGELOG.md
src/common/resources/exportConfigs.js
src/settings/BatchGroupConfigurationSettings/BatchGroupConfigurationForm.js
src/settings/BatchGroupConfigurationSettings/BatchGroupConfigurationSettings.js
test/bigtest/interactors/BatchGroupConfigurationSettingsInteractor.js
test/bigtest/network/configs/credentials.js
test/bigtest/tests/settings/batch-group-configuration-settings-test.js
test/bigtest/tests/settings/test-connection-test.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-110 …

UINV-110 Test voucher settings ftp connection

---

CHANGELOG.md
src/invoices/InvoiceForm/InvoiceForm.js

https://issues.folio.org/browse/UINV-139 …

UINV-139 Populate "Payment method"

---

CHANGELOG.md
src/invoices/AdjustmentsDetails/AdjustmentsDetails.js
src/settings/BatchGroupConfigurationSettings/BatchVoucherExportsList.js

https://issues.folio.org/browse/UINV-138 …

UINV-138 Align actions icons in table to right hand side of view pane

---

CHANGELOG.md
package.json
src/invoices/AdjustmentsForm/AdjustmentsForm.js
src/invoices/utils.js
src/settings/adjustments/SettingsAdjustmentsEditor/SettingsAdjustmentsEditor.js
src/settings/adjustments/SettingsAdjustmentsEditor/SettingsAdjustmentsEditorContainer.js
src/settings/adjustments/SettingsAdjustmentsList/SettingsAdjustmentsList.js
test/bigtest/interactors/InvoiceFormInteractor.js
test/bigtest/interactors/SettingsAdjustmentDetailsInteractor.js
test/bigtest/interactors/SettingsAdjustmentFormInteractor.js
test/bigtest/interactors/SettingsAdjustmentsListInteractor.js
test/bigtest/network/config.js
test/bigtest/tests/InvoiceCreate/InvoiceCreate-test.js
test/bigtest/tests/InvoiceEdit/InvoiceEdit-test.js
test/bigtest/tests/settings/setting-adjustments-list-test.js
test/bigtest/tests/settings/setting-create-adjustment-test.js
test/bigtest/tests/settings/setting-delete-adjustment-test.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-123
- Could be merged after [MODINVOSTO-58](https://issues.folio.org/browse/MODINVOSTO-58) [PR](https://github.com/folio-org/acq-models/pull/237)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to …

UINV-123 Add Export to accounting to Adjustments

---

Jenkinsfile
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLines.js

Align actions icons in table to right hand side of view pane(s)
https://issues.folio.org/browse/UINV-138 …

UINV-138 show arrow and align it to the right

---

package.json

https://issues.folio.org/browse/UINV-142 …

UINV-142 add get user by id permission

---

Jenkinsfile

to run tests on jenkins against bundle to avoid react tests mode and timeouts
While it's …

move jenkins param

---

translations/ui-invoice/ar.json
translations/ui-invoice/ca.json
translations/ui-invoice/da.json
translations/ui-invoice/de.json
translations/ui-invoice/en_GB.json
translations/ui-invoice/en_SE.json
translations/ui-invoice/en_US.json
translations/ui-invoice/es.json
translations/ui-invoice/es_419.json
translations/ui-invoice/es_ES.json
translations/ui-invoice/fr.json
translations/ui-invoice/fr_FR.json
translations/ui-invoice/he.json
translations/ui-invoice/hu.json
translations/ui-invoice/it_IT.json
translations/ui-invoice/ja.json
translations/ui-invoice/pt_BR.json
translations/ui-invoice/pt_PT.json
translations/ui-invoice/ru.json
translations/ui-invoice/ur.json
translations/ui-invoice/zh_CN.json
translations/ui-invoice/zh_TW.json

Update translation strings as of 20200415T205603

---

translations/ui-invoice/ar.json
translations/ui-invoice/ca.json
translations/ui-invoice/da.json
translations/ui-invoice/de.json
translations/ui-invoice/en_GB.json
translations/ui-invoice/en_SE.json
translations/ui-invoice/en_US.json
translations/ui-invoice/es.json
translations/ui-invoice/es_419.json
translations/ui-invoice/es_ES.json
translations/ui-invoice/fr.json
translations/ui-invoice/fr_FR.json
translations/ui-invoice/he.json
translations/ui-invoice/hu.json
translations/ui-invoice/it_IT.json
translations/ui-invoice/ja.json
translations/ui-invoice/pt_BR.json
translations/ui-invoice/pt_PT.json
translations/ui-invoice/ru.json
translations/ui-invoice/ur.json
translations/ui-invoice/zh_CN.json
translations/ui-invoice/zh_TW.json

Update translation strings as of 20200423T142657

---

CHANGELOG.md
src/common/components/ApprovedBy/ApprovedBy.js
src/common/constants/constants.js
src/invoices/InvoiceDetails/Information/Information.js
src/invoices/InvoiceForm/utils.js

Support breaking changes on the back-end for Limit document size feature
https://issues.folio.org/browse/UINV-146 …

UINV-146 change save document header

---

package.json

bump up invoice interface version

---

src/settings/BatchGroupConfigurationSettings/BatchGroupConfigurationSettings.js
src/settings/BatchGroupConfigurationSettings/utils.js
test/bigtest/interactors/BatchGroupConfigurationSettingsInteractor.js
test/bigtest/interactors/index.js
test/bigtest/tests/settings/batch-vouchet-manual-export-test.js

Refresh export status until it's not Pending or user navigates away
https://issues.folio.org/browse/UINV-104 …

UINV-104 refresh item status after manual export

---

CHANGELOG.md
src/invoices/InvoiceDetails/InvoiceDetailsContainer.js
src/invoices/InvoiceLineDetails/InvoiceLineDetailsContainer.js
src/invoices/InvoicesList/InvoicesList.js
src/invoices/InvoicesList/InvoicesListContainer.js
test/bigtest/network/config.js
test/bigtest/tests/InvoiceDetails/InvoiceDetails-test.js
test/bigtest/tests/InvoiceDetails/InvoiceDetailsApprove-test.js
test/bigtest/tests/InvoiceDetails/InvoiceDetailsPay-test.js
test/bigtest/tests/InvoiceLine/invoice-line-tags-test.js

Display record loading icon in view pane after user clicks action
https://issues.folio.org/browse/UINV-147 …

UINV-147 Display loading icon after any action

---

src/invoices/InvoiceDetails/InvoiceDetailsContainer.js

I take back my words regarding mutator - apparently it contains state. So memoized mutator captures first clicked invoice id. 
https://issues.folio.org/browse/UINV-147
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …

UINV-147 fix infinite spinner if click more than 1 invoice in list

---

CHANGELOG.md
package.json
src/invoices/InvoiceForm/InvoiceFormContainer.js
src/settings/BatchGroupsSettings/BatchGroupsSettings.js

https://issues.folio.org/browse/UINV-149 …

UINV-149 Update to Stripes v4

---

CHANGELOG.md
src/invoices/InvoiceForm/InvoiceDocumentsForm/InvoiceDocumentsForm.js
translations/ui-invoice/en.json
translations/ui-invoice/en_GB.json
translations/ui-invoice/en_SE.json
translations/ui-invoice/en_US.json

update size limit error message to include the size limit
https://issues.folio.org/browse/UINV-148 …

UINV-148 update size limit error message

---

translations/ui-invoice/ar.json
translations/ui-invoice/ca.json
translations/ui-invoice/da.json
translations/ui-invoice/de.json
translations/ui-invoice/en_GB.json
translations/ui-invoice/en_SE.json
translations/ui-invoice/en_US.json
translations/ui-invoice/es.json
translations/ui-invoice/es_419.json
translations/ui-invoice/fr.json
translations/ui-invoice/he.json
translations/ui-invoice/hu.json
translations/ui-invoice/ja.json
translations/ui-invoice/pt_BR.json
translations/ui-invoice/pt_PT.json
translations/ui-invoice/ru.json
translations/ui-invoice/ur.json
translations/ui-invoice/zh_TW.json

Update translation strings as of 20200519T123842

---

translations/ui-invoice/ru.json

Update translation strings as of 20200521T142352

---

src/invoices/AdjustmentsForm/AdjustmentsForm.js
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoiceLineDetails/InvoiceLineDetails.js
src/invoices/InvoiceLineForm/InvoiceLineForm.js
src/settings/adjustments/SettingsAdjustments.js
src/settings/adjustments/SettingsAdjustmentsView/SettingsAdjustmentsView.js
src/settings/adjustments/SettingsAdjustmentsView/SettingsAdjustmentsViewContainer.js

* fill fund code;
* don't use CalloutContext; …

fill fund code and refactoring

---

translations/ui-invoice/en_GB.json
translations/ui-invoice/en_SE.json
translations/ui-invoice/en_US.json

Update translation strings as of 20200522T132417

---

translations/ui-invoice/fr_FR.json

Update translation strings as of 20200526T141248

---

CHANGELOG.md
src/invoices/InvoiceDetails/InvoiceActions/InvoiceActions.js
src/invoices/InvoicesList/InvoicesList.js
test/bigtest/interactors/BatchGroupConfigurationSettingsInteractor.js
test/bigtest/interactors/InvoicesList.js
test/bigtest/tests/InvoicesList/InvoicesList-test.js

https://issues.folio.org/browse/UINV-153 …

UINV-153 Hide Delete option for invoices that are approved or paid

---

src/invoices/InvoiceForm/InvoiceDocumentsForm/InvoiceDocumentsForm.js
src/invoices/InvoiceForm/InvoiceFormContainer.js
src/invoices/Voucher/VoucherEditForm/VoucherEditContainer.js
src/settings/BatchGroupConfigurationSettings/BatchGroupConfigurationSettings.js
src/settings/BatchGroupConfigurationSettings/ExportVoucherButton/ExportVoucherButton.js
src/settings/VoucherNumber/SettingsVoucherNumberReset.js

UIOR-567 fix missing callouts

---

src/invoices/InvoiceLineDetails/ActionMenu.js
src/invoices/InvoiceLineDetails/InvoiceLineDetails.js
src/invoices/InvoiceLineDetails/InvoiceLineDetailsContainer.js

https://issues.folio.org/browse/UINV-153 …

UINV-153 hide delete for invoice line

---

package.json
src/invoices/InvoiceDetails/InvoiceDetailsContainer.js
src/invoices/InvoiceDetails/VoucherInformation/VoucherInformationContainer.js
src/invoices/InvoiceForm/InvoiceFormContainer.js
src/settings/BatchGroupConfigurationSettings/BatchGroupConfigurationSettings.js
test/bigtest/interactors/InvoiceLineDetailsTags.js

fix limit max

---

CHANGELOG.md
package.json
test/bigtest/interactors/InvoiceLineDetailsTags.js

Release v2.1.1

---

translations/ui-invoice/zh_CN.json

Update translation strings as of 20200615T161518

---

CHANGELOG.md
src/common/utils/getApproveErrorMessage.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-156 …

UINV-156 Support back-end changes related to accountingCode

---

CHANGELOG.md
src/common/utils/getApproveErrorMessage.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-156
original PR https://github.com/folio-org/ui-invoice/pull/290 …

UINV-156 Add error code for missed accountingCode

---

translations/ui-invoice/ar.json
translations/ui-invoice/ca.json
translations/ui-invoice/da.json
translations/ui-invoice/de.json
translations/ui-invoice/en_GB.json
translations/ui-invoice/en_SE.json
translations/ui-invoice/en_US.json
translations/ui-invoice/es.json
translations/ui-invoice/es_419.json
translations/ui-invoice/es_ES.json
translations/ui-invoice/fr.json
translations/ui-invoice/fr_FR.json
translations/ui-invoice/he.json
translations/ui-invoice/hu.json
translations/ui-invoice/it_IT.json
translations/ui-invoice/ja.json
translations/ui-invoice/pt_BR.json
translations/ui-invoice/pt_PT.json
translations/ui-invoice/ru.json
translations/ui-invoice/ur.json
translations/ui-invoice/zh_CN.json
translations/ui-invoice/zh_TW.json

Update translation strings as of 20200623T182030

---

translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-156?focusedCommentId=80439&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-80439 …

UINV-156 Update toast message

---

CHANGELOG.md
src/invoices/InvoicesList/constants.js

https://issues.folio.org/browse/UINV-164 …

UINV-164 Filter by Acquisitions Unit doesn't work

---

translations/ui-invoice/ca.json
translations/ui-invoice/da.json
translations/ui-invoice/de.json
translations/ui-invoice/en_GB.json
translations/ui-invoice/en_SE.json
translations/ui-invoice/en_US.json
translations/ui-invoice/es.json
translations/ui-invoice/es_419.json
translations/ui-invoice/es_ES.json
translations/ui-invoice/fr.json
translations/ui-invoice/fr_FR.json
translations/ui-invoice/he.json
translations/ui-invoice/hu.json
translations/ui-invoice/it_IT.json
translations/ui-invoice/ja.json
translations/ui-invoice/pt_PT.json
translations/ui-invoice/ru.json
translations/ui-invoice/ur.json
translations/ui-invoice/zh_CN.json
translations/ui-invoice/zh_TW.json

Update translation strings as of 20200624T130324

---

CHANGELOG.md
package.json
src/common/utils/getApproveErrorMessage.js
src/invoices/InvoiceLineForm/InvoiceLineForm.js
translations/ui-invoice/ar.json
translations/ui-invoice/ca.json
translations/ui-invoice/da.json
translations/ui-invoice/de.json
translations/ui-invoice/en.json
translations/ui-invoice/en_GB.json
translations/ui-invoice/en_SE.json
translations/ui-invoice/en_US.json
translations/ui-invoice/es.json
translations/ui-invoice/es_419.json
translations/ui-invoice/es_ES.json
translations/ui-invoice/fr.json
translations/ui-invoice/fr_FR.json
translations/ui-invoice/he.json
translations/ui-invoice/hu.json
translations/ui-invoice/it_IT.json
translations/ui-invoice/ja.json
translations/ui-invoice/pt_BR.json
translations/ui-invoice/pt_PT.json
translations/ui-invoice/ru.json
translations/ui-invoice/ur.json
translations/ui-invoice/zh_CN.json
translations/ui-invoice/zh_TW.json

UINV-160 Remaining amount of fund distribution not formatted by invoice currency setting

---

CHANGELOG.md
src/invoices/InvoicesList/InvoicesListSearchConfig.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-163 …

UINV-163 Search Keyword not working as expected

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/UINV-158 …

Release v2.1.3

---

CHANGELOG.md
package.json
translations/ui-invoice/en_GB.json
translations/ui-invoice/en_SE.json
translations/ui-invoice/en_US.json

backport patch release

---

CHANGELOG.md
src/common/resources/index.js
src/common/resources/orders.js
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceDetails/InvoiceLines/AddInvoiceLinesAction.js
src/invoices/InvoiceDetails/InvoiceLines/AddInvoiceLinesActionContainer.js
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLinesActions.js
test/bigtest/helpers/setup-application.js
test/bigtest/interactors/InvoiceDetails.js
test/bigtest/network/config.js
test/bigtest/tests/InvoiceDetails/addInvoiceLine-test.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-161
Add new prop `validateSelectedRecords` to pluggin for comparing POLs vendors and currencies with invoice
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number …

UINV-161 Alert user when adding pol to invoice that has a different currency or vendor that the invoice

---

translations/ui-invoice/ar.json
translations/ui-invoice/ca.json
translations/ui-invoice/da.json
translations/ui-invoice/de.json
translations/ui-invoice/en_GB.json
translations/ui-invoice/en_SE.json
translations/ui-invoice/en_US.json
translations/ui-invoice/es.json
translations/ui-invoice/es_419.json
translations/ui-invoice/es_ES.json
translations/ui-invoice/fr.json
translations/ui-invoice/fr_FR.json
translations/ui-invoice/he.json
translations/ui-invoice/hu.json
translations/ui-invoice/it_IT.json
translations/ui-invoice/ja.json
translations/ui-invoice/pt_BR.json
translations/ui-invoice/pt_PT.json
translations/ui-invoice/ru.json
translations/ui-invoice/ur.json
translations/ui-invoice/zh_CN.json
translations/ui-invoice/zh_TW.json

Update translation strings as of 20200707T213422

---

translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-161 …

UINV-161 Fix typos

---

translations/ui-invoice/ca.json
translations/ui-invoice/da.json
translations/ui-invoice/de.json
translations/ui-invoice/en_GB.json
translations/ui-invoice/en_SE.json
translations/ui-invoice/en_US.json
translations/ui-invoice/es.json
translations/ui-invoice/es_419.json
translations/ui-invoice/es_ES.json
translations/ui-invoice/fr.json
translations/ui-invoice/fr_FR.json
translations/ui-invoice/he.json
translations/ui-invoice/hu.json
translations/ui-invoice/it_IT.json
translations/ui-invoice/ja.json
translations/ui-invoice/pt_BR.json
translations/ui-invoice/pt_PT.json
translations/ui-invoice/ru.json
translations/ui-invoice/ur.json
translations/ui-invoice/zh_CN.json
translations/ui-invoice/zh_TW.json

Update translation strings as of 20200709T123052

---

translations/ui-invoice/pt_BR.json

Update translation strings as of 20200710T132222

---

src/invoices/InvoiceLineDetails/InvoiceLineInformation.js
src/invoices/InvoicesList/InvoicesList.js
src/settings/adjustments/SettingsAdjustmentsView/SettingsAdjustmentsView.js

Fix accessibility errors
- id attribute value must be unique for InvoiceList columns
- Form elements must have labels for Checkboxes in details screens …

Fix accessibility errors

---

CHANGELOG.md
src/invoices/InvoicesList/InvoicesListContainer.js

https://issues.folio.org/browse/UINV-167 …

UINV-167 Cannot filter invoice by invoice line tags

---

CHANGELOG.md
package.json
src/invoices/InvoiceForm/InvoiceForm.js

https://issues.folio.org/browse/UISACQCOMP-2 …

UISACQCOMP-2 CurrencySelect values are not translated

---

translations/ui-invoice/fr_FR.json
translations/ui-invoice/ru.json

Update translation strings as of 20200716T140311

---

translations/ui-invoice/zh_CN.json

Update translation strings as of 20200721T202356

---

src/invoices/InvoiceDetails/InvoiceLines/AddInvoiceLinesActionContainer.js

Fix adding invoice line based on POL

---

CHANGELOG.md
package.json
src/invoices/InvoiceDetails/InvoiceBatchVoucherExport/InvoiceBatchVoucherExport.js
src/invoices/InvoiceDetails/InvoiceBatchVoucherExport/index.js
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceDetails/InvoiceDetailsContainer.js
src/invoices/constants.js
src/settings/BatchGroupConfigurationSettings/BatchVoucherExportsList.js
src/settings/BatchGroupConfigurationSettings/ExportVoucherButton/ExportVoucherButton.js
test/bigtest/interactors/InvoiceDetails.js
test/bigtest/tests/InvoiceCreate/InvoiceCreate-test.js
test/bigtest/tests/InvoiceCreate/InvoiceCreateDocuments-test.js
test/bigtest/tests/InvoiceDetails/invoiceVoucherExport-test.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-159 …

UINV-159 Display voucher export details accordion

---

CHANGELOG.md
src/common/constants/constants.js
src/common/utils/invoiceUtils.js
src/invoices/InvoiceForm/InvoiceForm.js

https://issues.folio.org/browse/UINV-174 …

UINV-174 Approve status can be selected during invoice create/edit

---

translations/ui-invoice/ar.json
translations/ui-invoice/ca.json
translations/ui-invoice/da.json
translations/ui-invoice/de.json
translations/ui-invoice/en_GB.json
translations/ui-invoice/en_SE.json
translations/ui-invoice/en_US.json
translations/ui-invoice/es.json
translations/ui-invoice/es_419.json
translations/ui-invoice/es_ES.json
translations/ui-invoice/fr.json
translations/ui-invoice/fr_FR.json
translations/ui-invoice/he.json
translations/ui-invoice/hu.json
translations/ui-invoice/it_IT.json
translations/ui-invoice/ja.json
translations/ui-invoice/pt_BR.json
translations/ui-invoice/pt_PT.json
translations/ui-invoice/ru.json
translations/ui-invoice/ur.json
translations/ui-invoice/zh_CN.json
translations/ui-invoice/zh_TW.json

Update translation strings as of 20200811T193833

---

package.json
src/invoices/InvoiceDetails/InvoiceDetailsContainer.js

UINV-159 Add missed permissions

---

CHANGELOG.md
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceDetails/InvoiceDetailsContainer.js
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLines.js
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLinesContainer.js
translations/ui-invoice/en.json

Display warning when POL is Fully paid
https://issues.folio.org/browse/UINV-173 
While it's …

UINV-173 Display warning when POL is Fully paid

---

translations/ui-invoice/ar.json
translations/ui-invoice/ca.json
translations/ui-invoice/da.json
translations/ui-invoice/de.json
translations/ui-invoice/en_GB.json
translations/ui-invoice/en_SE.json
translations/ui-invoice/en_US.json
translations/ui-invoice/es.json
translations/ui-invoice/es_419.json
translations/ui-invoice/es_ES.json
translations/ui-invoice/fr.json
translations/ui-invoice/fr_FR.json
translations/ui-invoice/he.json
translations/ui-invoice/hu.json
translations/ui-invoice/it_IT.json
translations/ui-invoice/ja.json
translations/ui-invoice/pt_BR.json
translations/ui-invoice/pt_PT.json
translations/ui-invoice/ru.json
translations/ui-invoice/ur.json
translations/ui-invoice/zh_CN.json
translations/ui-invoice/zh_TW.json

Update translation strings as of 20200813T135432

---

CHANGELOG.md
src/settings/VoucherNumber/SettingsVoucherNumberForm.js
test/bigtest/tests/InvoiceCreate/InvoiceCreateDocuments-test.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-70
BE allows any Unicode **letters** for voucher number prefix- https://github.com/folio-org/mod-invoice/blob/925a0e1156c462640070980fb8fcac24762fc311/src/main/java/org/folio/rest/impl/InvoiceHelper.java#L664
But at the same voucher number could include only alphanumeric characters - https://github.com/folio-org/acq-models/blob/master/mod-invoice-storage/schemas/voucher.json#L83 
- Are the …

Add validation to voucher number prefix on UI

---

CHANGELOG.md
src/invoices/InvoiceDetails/InvoiceDetailsContainer.js
src/invoices/InvoiceForm/InvoiceForm.js
test/bigtest/interactors/InvoiceLineDetailsTags.js
test/bigtest/interactors/common/TagsPane.js
test/bigtest/tests/InvoiceDetails/InvoiceDetailsApprove-test.js
test/bigtest/tests/InvoiceDetails/InvoiceDetailsPay-test.js

https://issues.folio.org/browse/UINV-83 …

UINV-83 test error message

---

translations/ui-invoice/ar.json
translations/ui-invoice/ca.json
translations/ui-invoice/da.json
translations/ui-invoice/de.json
translations/ui-invoice/en_GB.json
translations/ui-invoice/en_SE.json
translations/ui-invoice/en_US.json
translations/ui-invoice/es.json
translations/ui-invoice/es_419.json
translations/ui-invoice/es_ES.json
translations/ui-invoice/fr.json
translations/ui-invoice/fr_FR.json
translations/ui-invoice/he.json
translations/ui-invoice/hu.json
translations/ui-invoice/it_IT.json
translations/ui-invoice/ja.json
translations/ui-invoice/pt_BR.json
translations/ui-invoice/pt_PT.json
translations/ui-invoice/ru.json
translations/ui-invoice/ur.json
translations/ui-invoice/zh_CN.json
translations/ui-invoice/zh_TW.json

Update translation strings as of 20200820T141724

---

translations/ui-invoice/fr_FR.json
translations/ui-invoice/pt_BR.json
translations/ui-invoice/zh_CN.json

Update translation strings as of 20200824T140725

---

src/invoices/InvoiceDetails/InvoiceLines/InvoiceLines.js

https://issues.folio.org/browse/UINV-173 …

UINV-173 add space before title

---

CHANGELOG.md
src/invoices/InvoiceForm/InvoiceForm.js

https://issues.folio.org/browse/UIORGS-186 …

UIORGS-186 Export to accounting logic to invoice

---

CHANGELOG.md
package.json
src/settings/adjustments/util.js

https://issues.folio.org/browse/UINV-177
https://issues.folio.org/browse/UINV-178
While it's …

UINV-177 Adjustment settings are not in alpha order

---

src/settings/adjustments/util.js

https://issues.folio.org/browse/UINV-177 …

UINV-177 fix case insensitive sorting

---

CHANGELOG.md
src/invoices/InvoiceDetails/Information/Information.js
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceDetails/InvoiceDetailsContainer.js
src/invoices/InvoiceForm/InvoiceForm.js

https://issues.folio.org/browse/UINV-182 …

UINV-182 Invoice record UX updates

---

src/invoices/AdjustmentsDetails/AdjustmentsDetails.js

https://issues.folio.org/browse/UINV-178 …

UINV-178 use FrontendSortingMCL for client-side sorting

---

translations/ui-invoice/ar.json
translations/ui-invoice/es.json
translations/ui-invoice/es_419.json
translations/ui-invoice/es_ES.json
translations/ui-invoice/fr_FR.json

Update translation strings as of 20200901T173106

---

src/invoices/InvoiceForm/InvoiceForm.js

https://issues.folio.org/browse/UINV-182 …

UINV-182 Move "Lock total" field down

---

CHANGELOG.md
src/invoices/InvoiceLineDetails/InvoiceLineDetails.js
src/invoices/InvoiceLineDetails/InvoiceLineDetailsContainer.js
src/invoices/InvoiceLineDetails/InvoiceLineInformation.js
src/invoices/InvoiceLineForm/InvoiceLineForm.js

https://issues.folio.org/browse/UINV-183 …

UINV-183 Invoice line record ux update

---

CHANGELOG.md
src/invoices/InvoiceDetails/VoucherInformation/VoucherInformation.js
src/invoices/Voucher/VoucherDetails.js

https://issues.folio.org/browse/UINV-184 …

UINV-184 Voucher currency Not based on fiscal year

---

translations/ui-invoice/pt_BR.json

Update translation strings as of 20200922T125348

---

CHANGELOG.md
src/settings/BatchGroupConfigurationSettings/BatchVoucherExportsList.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-188 …

UINV-188 Display batch voucher error message beside "Status"

---

CHANGELOG.md
src/common/components/VoucherNumber/FieldVoucherNumber.js
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLines.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-187 …

UINV-187 Update invoice view pane

---

src/invoices/InvoiceForm/InvoiceForm.js

UINV-186 Fix: invoice date is required field

---

src/invoices/InvoiceForm/CurrentExchangeRate/CurrentExchangeRate.js
src/invoices/InvoiceForm/InvoiceForm.js

User can edit the exchange rate field until the invoice is paid …

UINV-195 Exchange rate is text for paid invoice

---

src/invoices/InvoiceForm/CurrentExchangeRate/CurrentExchangeRate.js
src/invoices/InvoiceForm/InvoiceForm.js

Fix exchange rate

---

translations/ui-invoice/es.json
translations/ui-invoice/es_419.json
translations/ui-invoice/es_ES.json

Update translation strings as of 20201016T144229

---

CHANGELOG.md
src/invoices/InvoiceDetails/Information/Information.js
src/invoices/InvoiceDetails/InvoiceDetails.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-200 …

UINV-200 Add invoice note in the view pane

---

src/common/resources/invoice.js

fix the typo, return `false` does nothing, it should be a function …

remove extra update of documents list

---

CHANGELOG.md
src/invoices/InvoicesList/InvoicesListContainer.js

Basically, we need separate filter queries for date values and datetime. Datime should be converted in the UTC, dates should go as user entered, since it's the same as user enters them through calendar field
https://issues.folio.org/browse/UINV-202
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …

UINV-202 introduce datetime and date range filters

---

translations/ui-invoice/fr_FR.json

Update translation strings as of 20201110T192302

---

CHANGELOG.md
package.json
src/common/constants/constants.js
src/invoices/Invoices.js
src/invoices/Voucher/Voucher.js
src/invoices/Voucher/VoucherEditForm/VoucherEditContainer.js
src/invoices/Voucher/VoucherViewLayer.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-199
Permissions spreadsheet - https://docs.google.com/spreadsheets/d/1IJnlWvi4k-wFatDNimx9fQ375evHSIIxtGMookHvs-I/edit#gid=443204981
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …

UINV-199 Update invoice CRUD permissions

---

package.json

Fix acquisitions-units permission names - https://github.com/folio-org/mod-invoice/blob/master/descriptors/ModuleDescriptor-template.json#L788 …

UINV-199 Fix acq-units permission names

---

src/invoices/InvoiceForm/InvoiceForm.js

Fix missed acq-units permissions

---

CHANGELOG.md
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoiceForm/InvoiceForm.test.js
test/bigtest/interactors/InvoiceFormInteractor.js
test/bigtest/tests/InvoiceEdit/InvoiceEdit-test.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-191 …

UINV-191 Implement Lock total invoice form logic

---

CHANGELOG.md
src/common/constants/constants.js
src/invoices/InvoiceDetails/utils.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-190 …

UINV-190 Lock total must equal Calculated total to approve invoice

---

translations/ui-invoice/en.json

UINV-190 fix translation

---

CHANGELOG.md
src/invoices/InvoiceDetails/Information/Information.js
src/invoices/InvoiceDetails/Information/Information.test.js
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceForm/InvoiceForm.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-208 …

UINV-208 Display lock total on invoice view

---

CHANGELOG.md
src/invoices/InvoiceDetails/ApproveConfirmationModal/ApproveConfirmationModal.js
src/invoices/InvoiceDetails/ApproveConfirmationModal/ApproveConfirmationModal.test.js
src/invoices/InvoiceDetails/ApproveConfirmationModal/DuplicateInvoiceList/DuplicateInvoiceList.js
src/invoices/InvoiceDetails/ApproveConfirmationModal/DuplicateInvoiceList/DuplicateInvoiceList.test.js
src/invoices/InvoiceDetails/ApproveConfirmationModal/DuplicateInvoiceList/index.js
src/invoices/InvoiceDetails/ApproveConfirmationModal/index.js
src/invoices/InvoiceDetails/ApproveConfirmationModal/useDuplicateInvoice.js
src/invoices/InvoiceDetails/InvoiceDetails.js
test/bigtest/interactors/ApproveInvoiceModalInteractor.js
test/bigtest/tests/InvoiceDetails/InvoiceDetailsApprove-test.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-192 …

UINV-192 Show the possible duplicate modal at point of invoice approval

---

CHANGELOG.md
PERSONAL_DATA_DISCLOSURE.md

https://issues.folio.org/browse/UINV-212 …

UINV-212 Add personal data disclosure form

---

CHANGELOG.md
src/settings/BatchGroupConfigurationSettings/BatchGroupConfigurationForm.js

https://issues.folio.org/browse/UINV-210 …

UINV-210 make username not required

---

CHANGELOG.md
src/common/utils/getAccountingCodeOptions.js
src/invoices/InvoiceForm/InvoiceForm.js

Another field is introduced - invoice acc number, so select should set this together with acc code. But since Acc number is unique - ui representation should set acc number in the first place
https://issues.folio.org/browse/UINV-169
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …

UINV-169 select acc number(unique) instead of code

---

CHANGELOG.md
package.json

backport release and bump up stripes

---

package.json

https://issues.folio.org/browse/UINV-221 …

Update stripes-cli to v2

---

CHANGELOG.md
src/invoices/InvoiceDetails/utils.js
src/invoices/InvoiceLineDetails/InvoiceLineInformation.js
src/invoices/InvoiceLineForm/InvoiceLineForm.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-165 …

UINV-165 vendor ref number and type are repeatable

---

CHANGELOG.md
src/invoices/InvoiceDetails/Information/Information.js
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoicesList/InvoicesListContainer.js
src/invoices/InvoicesList/InvoicesListFilters/InvoicesListFilters.js
src/invoices/InvoicesList/constants.js
translations/ui-invoice/en.json

Display and filter paymentDate in Invoice module
https://issues.folio.org/browse/UINV-224 …

UINV-224 show and filter by payment date

---

CHANGELOG.md
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLines.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-225 …

UINV-225 Update view for Vendor reference number

---

CHANGELOG.md
src/invoices/InvoiceDetails/ExtendedInformation/ExtendedInformation.js
src/invoices/InvoiceDetails/ExtendedInformation/ExtendedInformation.test.js
src/invoices/InvoiceDetails/ExtendedInformation/index.js
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/constants.js

https://issues.folio.org/browse/UINV-222 …

UINV-222 Add Extended Info accordion to Invoice

---

CHANGELOG.md
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-170 …

UINV-170 delete invoice with attached document

---

CHANGELOG.md
src/common/constants/constants.js
src/invoices/InvoiceDetails/utils.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-215 …

UINV-215 Prevent approval of invoice when organization IS NOT a vendor

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/UINV-229 …

UINV-229 backport release to master

---

CHANGELOG.md
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLines.js

https://issues.folio.org/browse/UINV-230
Display invoice line number instead of `rowIndex` number …

UINV-230 Display Invoice line number and add sorting

---

src/invoices/Voucher/useVoucher.js

UINV-226 fix voucher lines search params

---

CHANGELOG.md
src/invoices/Voucher/VoucherDetails.js
src/invoices/Voucher/VoucherDetails.test.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-227 …

UINV-227 Include account number from Invoice information in voucher

---

src/invoices/Voucher/VoucherDetails.js
src/invoices/Voucher/VoucherDetails.test.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-227?focusedCommentId=100078&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-100078 …

UINV-227 Remove no account value (use default hyphen)

---

CHANGELOG.md
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLines.js

https://issues.folio.org/browse/UINV-240 …

UINV-240 Invoice lines are not in numerical order

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/UINV-244 …

UINV-244 Cannot delete attached file from invoice

---

CHANGELOG.md
src/invoices/AdjustmentsForm/AdjustmentsForm.js
src/settings/adjustments/SettingsAdjustmentsEditor/SettingsAdjustmentsEditor.js

https://issues.folio.org/browse/UINV-248 …

UINV-248 Cannot approve invoice with a certain type of adjustment

---

CHANGELOG.md
src/invoices/InvoiceDetails/InvoiceBatchVoucherExport/InvoiceBatchVoucherExport.js

https://issues.folio.org/browse/UINV-252 …

UINV-252 Batch file status not displaying properly

---

package.json

Missed permissions

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/UIOR-678 …

UIOR-678 Permissions for Expense class filter (find-po-line-plugin)

---

src/invoices/InvoiceDetails/InvoiceActions/InvoiceActions.js
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/Voucher/VoucherViewLayer.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-232 …

UINV-232 Add Print action and icon

---

src/invoices/InvoiceDetails/InvoiceDetailsContainer.js
src/invoices/InvoicesList/InvoicesList.js

https://issues.folio.org/browse/UINV-253 …

UINV-253 Resizable Panes - Persistence

---

src/invoices/PrintVoucher/PrintVoucherContainer.js
translations/ui-invoice/en.json

fix Review comment - hide confirmation. But from my perspective it's better still load data after user clicked Print and we can show spinner in modal.
https://issues.folio.org/browse/UINV-232
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …

UINV-232 hide confirmation

---

src/invoices/PrintVoucher/PrintContent/PrintContent.css
src/invoices/PrintVoucher/PrintContent/PrintContent.js
test/bigtest/network/factories/voucherLine.js

https://issues.folio.org/browse/UINV-235 …

UINV-235-remove-empty-sheet

---

src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoiceLineDetails/InvoiceLineDetails.js
src/invoices/InvoiceLineForm/InvoiceLineForm.js
src/invoices/Invoices.js
src/invoices/InvoicesList/InvoicesList.js
src/invoices/Voucher/VoucherEditForm/VoucherEditForm.js
src/invoices/Voucher/VoucherView.js
src/invoices/Voucher/VoucherViewLayer.js

https://issues.folio.org/browse/UINV-237 …

UINV-237 Apply baseline shortcut keys

---

src/invoices/InvoiceDetails/InvoiceActions/InvoiceActions.js
src/invoices/InvoiceDetails/InvoiceDetails.js

https://issues.folio.org/browse/UINV-238 …

UINV-238 AcqUnits restrictions

---

src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceLineDetails/InvoiceLineDetails.js
src/invoices/InvoicesList/InvoicesList.js
src/invoices/Voucher/VoucherViewLayer.js

https://issues.folio.org/browse/UINV-237 …

UINV-237 Shortcut keys: check permissions

---

CHANGELOG.md
src/invoices/Invoices.js

https://issues.folio.org/browse/UINV-257 …

UINV-257 Implement Keyboard shortcuts modal

---

CHANGELOG.md
src/common/hooks/index.js
src/common/hooks/useInvoiceMutation/index.js
src/common/hooks/useInvoiceMutation/useInvoiceMutation.js
src/common/hooks/useInvoiceMutation/useInvoiceMutation.test.js
src/invoices/InvoiceDetails/InvoiceDetailsContainer.js

https://issues.folio.org/browse/UINV-262
use react-query instead of stripes-connect as it has a bug with router props cache …

UINV-262 Invoice is only approved when user clicks 'approve and pay'

---

src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoiceLineDetails/InvoiceLineDetails.js
src/invoices/InvoiceLineForm/InvoiceLineForm.js
src/invoices/Invoices.js
src/invoices/InvoicesList/InvoicesList.js
src/invoices/Voucher/VoucherEditForm/VoucherEditForm.js
src/invoices/Voucher/VoucherViewLayer.js

use common handler handleKeyCommand

---

CHANGELOG.md
Jenkinsfile
package.json

https://issues.folio.org/browse/UINV-251 …

UIINV-251 Compile Translation Files into AST Format

---

CHANGELOG.md
src/common/hooks/index.js
src/common/hooks/useOrderLine/index.js
src/common/hooks/useOrderLine/useOrderLine.js
src/common/hooks/useOrderLine/useOrderLine.test.js
src/invoices/InvoiceDetails/utils.js
src/invoices/InvoiceLineForm/InvoiceLineForm.js
src/invoices/InvoiceLineForm/InvoiceLineFormContainer.js
src/invoices/InvoiceLineForm/POLineField/POLineField.js
src/invoices/InvoiceLineForm/POLineField/POLineField.test.js
src/invoices/InvoiceLineForm/POLineField/index.js
src/invoices/utils.js
src/invoices/utils.test.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-193 …

UIINV-193 Allow user to link an invoice line to a PO line after the invoice line has been created

---

src/invoices/InvoiceLineForm/InvoiceLineForm.js

https://issues.folio.org/browse/UINV-193 …

UINV-193 relink POL should not change price and quantity

---

src/invoices/InvoiceLineForm/InvoiceLineForm.js

https://issues.folio.org/browse/UINV-193 …

UINV-193 POL link change should update limit fields for EDI

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/UINV-260 …

UINV-260 Update package.json

---

CHANGELOG.md
src/common/hooks/index.js
src/common/hooks/useInvoiceLineMutation/index.js
src/common/hooks/useInvoiceLineMutation/useInvoiceLineMutation.js
src/common/hooks/useInvoiceLineMutation/useInvoiceLineMutation.test.js
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceDetails/InvoiceDetailsContainer.js
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLinePOLineNumber/InvoiceLinePOLineNumber.js
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLinePOLineNumber/index.js
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLines.js
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLinesContainer.js
test/bigtest/interactors/InvoiceDetails.js
test/bigtest/tests/InvoiceLine/invoice-line-edit-test.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-267 …

UINV-267 Allow user to link an invoice line to a PO line from the invoice view

---

CHANGELOG.md
src/invoices/InvoiceDetails/InvoiceDetails.js

https://issues.folio.org/browse/UINV-273 …

UINV-273 Invoice FundDistr not showing amount

---

CHANGELOG.md
src/invoices/InvoicesList/InvoicesListContainer.js
src/invoices/InvoicesList/InvoicesListContainer.test.js

https://issues.folio.org/browse/UINV-275 …

UINV-275 Search not working for some acc codes

---

CHANGELOG.md
src/invoices/InvoicesList/InvoicesListContainer.test.js
src/invoices/InvoicesList/InvoicesListSearchConfig.js

https://issues.folio.org/browse/UINV-162 …

UINV-162 Search invoice by PO number

---

CHANGELOG.md
src/invoices/InvoicesList/InvoicesListContainer.js
src/invoices/InvoicesList/InvoicesListFilters/__snapshots__/InvoicesListFilters.test.js.snap
test/bigtest/tests/InvoiceCreate/InvoiceCreate-test.js
test/bigtest/tests/InvoiceCreate/InvoiceCreateDocuments-test.js
test/bigtest/tests/InvoiceDetails/InvoiceDetailsPay-test.js
test/bigtest/tests/InvoiceDetails/InvoiceDetailsTags-test.js
test/bigtest/tests/InvoiceDetails/addInvoiceLine-test.js
test/bigtest/tests/InvoiceDetails/editVoucherInformation-test..js
test/bigtest/tests/InvoiceDetails/invoiceVoucherExport-test.js
test/bigtest/tests/InvoiceDetails/voucherInformation-test.js
test/bigtest/tests/InvoiceEdit/InvoiceEdit-test.js
test/bigtest/tests/InvoiceEdit/InvoiceEditDocuments-test.js
test/bigtest/tests/InvoiceLine/invoice-line-create-test.js
test/bigtest/tests/InvoiceLine/invoice-line-details-test.js
test/bigtest/tests/InvoiceLine/invoice-line-tags-test.js
test/bigtest/tests/InvoicesList/InvoicesList-test.js
test/bigtest/tests/settings/batch-group-configuration-settings-test.js
test/bigtest/tests/settings/batch-groups-settings-test.js
test/bigtest/tests/settings/batch-voucher-exports-test.js
test/bigtest/tests/settings/batch-vouchet-manual-export-test.js
test/bigtest/tests/settings/setting-adjustments-list-test.js
test/bigtest/tests/settings/setting-create-adjustment-test.js
test/bigtest/tests/settings/setting-delete-adjustment-test.js
test/bigtest/tests/settings/setting-voucher-number-test.js
test/bigtest/tests/settings/settings-approvals.js
test/bigtest/tests/settings/test-connection-test.js

UINV-286 Filter by Acquisition units in Invoice app is not worked

---

CHANGELOG.md
src/invoices/PrintVoucher/PrintContent/PrintContent.css
src/invoices/PrintVoucher/PrintVoucherContainer.js
src/invoices/PrintVoucher/utils.js

https://issues.folio.org/browse/UINV-288 …

UINV-288 global CSS styles force landscape printing in other modules

---

CHANGELOG.md
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLineOrderLineNumber/InvoiceLineOrderLineNumber.js

https://issues.folio.org/browse/UINV-290 …

UINV-290 Add hover text to invoice link icon

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/UINV-297 …

UINV-297 UINV (ui-invoice) R2 Hotfix #2 release

---

package.json

bump up "finance.expense-classes" interface

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/UINV-284 …

UINV-284 increment stripes to v7

---

CHANGELOG.md
src/invoices/InvoicesList/InvoicesList.js
src/invoices/InvoicesList/InvoicesList.test.js
src/invoices/InvoicesList/InvoicesListContainer.js
src/invoices/InvoicesList/InvoicesListContainer.test.js
src/invoices/InvoicesList/constants.js
src/invoices/InvoicesList/hooks/index.js
src/invoices/InvoicesList/hooks/useBuildQuery/index.js
src/invoices/InvoicesList/hooks/useBuildQuery/useBuildQuery.js
src/invoices/InvoicesList/hooks/useBuildQuery/useBuildQuery.test.js
src/invoices/InvoicesList/hooks/useInvoices/index.js
src/invoices/InvoicesList/hooks/useInvoices/useInvoices.js
src/invoices/InvoicesList/hooks/useInvoices/useInvoices.test.js
src/invoices/InvoicesList/index.js
test/bigtest/tests/InvoicesList/InvoicesList-test.js

https://issues.folio.org/browse/UINV-293 …

UINV-293 Invoices - Implement Next/Prev pagination

---

src/invoices/InvoicesList/InvoicesList.js
src/invoices/InvoicesList/InvoicesListContainer.js
src/invoices/InvoicesList/constants.js

UINV-293 use common result_count_increment

---

CHANGELOG.md
src/invoices/InvoiceDetails/__snapshots__/InvoiceDetails.test.js.snap
src/invoices/InvoiceForm/__snapshots__/InvoiceForm.test.js.snap
src/invoices/InvoiceLineDetails/__snapshots__/InvoiceLineDetails.test.js.snap
src/invoices/InvoiceLineForm/__snapshots__/InvoiceLineForm.test.js.snap
src/invoices/InvoicesList/InvoicesListFilters/InvoicesListFilters.js
src/invoices/InvoicesList/InvoicesListFilters/__snapshots__/InvoicesListFilters.test.js.snap
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-302 …

UINV-302 Filter label contains extra 's'

---

CHANGELOG.md
src/settings/InvoiceSettings.js
src/settings/adjustments/SettingsAdjustmentsEditor/SettingsAdjustmentsEditor.js
src/settings/adjustments/SettingsAdjustmentsList/SettingsAdjustmentsList.js
src/settings/adjustments/SettingsAdjustmentsList/SettingsAdjustmentsList.test.js
src/settings/adjustments/SettingsAdjustmentsList/__snapshots__/SettingsAdjustmentsList.test.js.snap
src/settings/adjustments/SettingsAdjustmentsView/SettingsAdjustmentsView.js
src/settings/adjustments/SettingsAdjustmentsView/SettingsAdjustmentsView.test.js
src/settings/adjustments/SettingsAdjustmentsView/SettingsAdjustmentsViewContainer.js
src/settings/adjustments/SettingsAdjustmentsView/__snapshots__/SettingsAdjustmentsView.test.js.snap

https://issues.folio.org/browse/UINV-304 …

UINV-304 Settings (Invoice adjustments) | Apply baseline keyboard shortcuts

---

CHANGELOG.md
package.json
src/invoices/InvoiceDetails/InvoiceActions/InvoiceActions.js

https://issues.folio.org/browse/UINV-310 …

UINV-310 Hide cancel invoice button

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/UINV-328 …

UINV-328 UINV (ui-invoice) R3 Bugfix release

---

CHANGELOG.md
src/common/utils/getAccountingCodeOptions.js
src/invoices/AdjustmentsForm/AdjustmentsForm.js
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoiceForm/InvoiceForm.test.js
src/invoices/InvoiceForm/InvoiceFormContainer.js
src/invoices/InvoiceForm/__snapshots__/InvoiceForm.test.js.snap
src/invoices/InvoiceForm/utils.js
src/invoices/InvoiceForm/utils.test.js
test/bigtest/tests/InvoiceEdit/InvoiceEdit-test.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-324 …

UINV-324 Indicate accounting code is required

---

CHANGELOG.md
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLines.js
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLinesContainer.js
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLinesContainer.test.js
src/invoices/InvoiceDetails/InvoiceLines/__snapshots__/InvoiceLines.test.js.snap
src/invoices/InvoiceDetails/InvoiceLines/hooks/index.js
src/invoices/InvoiceDetails/InvoiceLines/hooks/useInvoiceOrders/index.js
src/invoices/InvoiceDetails/InvoiceLines/hooks/useInvoiceOrders/useInvoiceOrders.js
src/invoices/InvoiceDetails/InvoiceLines/hooks/useInvoiceOrders/useInvoiceOrders.test.js

https://issues.folio.org/browse/UINV-333 …

UINV-333 Add POL vendor code to invoice line display

---

package.json
src/invoices/InvoiceDetails/InvoiceDetailsContainer.js
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLines.js
src/invoices/InvoiceLineForm/InvoiceLineForm.js
src/invoices/InvoicesList/InvoicesListFilters/InvoicesListFilters.js
src/invoices/InvoicesList/hooks/useBuildQuery/useBuildQuery.js
src/invoices/PrintVoucher/ComponentToPrint/ComponentToPrint.js
src/invoices/PrintVoucher/PrintVoucherContainer.js
src/invoices/Voucher/VoucherViewLayer.js

bump up es-lint version

---

CHANGELOG.md
src/common/hooks/index.js
src/common/hooks/useInvoiceLine/index.js
src/common/hooks/useInvoiceLine/useInvoiceLine.js
src/common/hooks/useInvoiceLine/useInvoiceLine.test.js
src/common/hooks/useInvoiceLineMutation/useInvoiceLineMutation.js
src/common/hooks/useInvoiceLineMutation/useInvoiceLineMutation.test.js
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLineOrderLineLink/InvoiceLineOrderLineLink.js
src/invoices/InvoiceLineDetails/InvoiceLineDetails.js
src/invoices/InvoiceLineDetails/InvoiceLineDetails.test.js
src/invoices/InvoiceLineDetails/InvoiceLineDetailsContainer.js
src/invoices/InvoiceLineDetails/InvoiceLineDetailsContainer.test.js
src/invoices/InvoiceLineDetails/OtherRelatedInvoiceLines/OtherRelatedInvoiceLines.js
src/invoices/InvoiceLineDetails/OtherRelatedInvoiceLines/OtherRelatedInvoiceLines.test.js
src/invoices/InvoiceLineDetails/OtherRelatedInvoiceLines/index.js
src/invoices/InvoiceLineDetails/OtherRelatedInvoiceLines/useOtherRelatedInvoiceLines.js
src/invoices/InvoiceLineDetails/OtherRelatedInvoiceLines/useOtherRelatedInvoiceLines.test.js
src/invoices/InvoiceLineDetails/__snapshots__/InvoiceLineDetails.test.js.snap
src/invoices/InvoiceLineDetails/index.js
src/invoices/constants.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-331 …

UINV-331 Display past payments for a POL on an invoice line

---

CHANGELOG.md
src/invoices/InvoicesList/InvoicesListFilters/BatchGroupFilter/BatchGroupFilter.js
src/invoices/InvoicesList/InvoicesListFilters/BatchGroupFilter/BatchGroupFilter.test.js
src/invoices/InvoicesList/InvoicesListFilters/BatchGroupFilter/index.js
src/invoices/InvoicesList/InvoicesListFilters/BatchGroupFilter/useBatchGroupOptions.js
src/invoices/InvoicesList/InvoicesListFilters/BatchGroupFilter/useBatchGroupOptions.test.js
src/invoices/InvoicesList/InvoicesListFilters/InvoicesListFilters.js
src/invoices/InvoicesList/InvoicesListFilters/InvoicesListFilters.test.js
src/invoices/InvoicesList/InvoicesListFilters/__snapshots__/InvoicesListFilters.test.js.snap
src/invoices/InvoicesList/constants.js

https://issues.folio.org/browse/UINV-335 …

UINV-335 Filter invoices by Batch group

---

src/invoices/AdjustmentsDetails/__snapshots__/AdjustmentsDetails.test.js.snap
src/invoices/InvoiceDetails/DocumentsDetails/__snapshots__/DocumentsDetails.test.js.snap
src/invoices/InvoiceDetails/InvoiceLines/__snapshots__/InvoiceLines.test.js.snap
src/invoices/InvoiceDetails/VoucherInformation/__snapshots__/VoucherInformation.test.js.snap
src/invoices/InvoiceDetails/__snapshots__/InvoiceDetails.test.js.snap
src/invoices/InvoiceForm/__snapshots__/InvoiceForm.test.js.snap
src/invoices/InvoiceLineDetails/__snapshots__/InvoiceLineDetails.test.js.snap
src/invoices/InvoiceLineForm/__snapshots__/InvoiceLineForm.test.js.snap
src/invoices/InvoicesList/InvoicesListFilters/__snapshots__/InvoicesListFilters.test.js.snap
src/invoices/Voucher/VoucherEditForm/__snapshots__/VoucherEditForm.test.js.snap
src/invoices/Voucher/__snapshots__/VoucherLinesDetails.test.js.snap
src/invoices/Voucher/__snapshots__/VoucherViewLayer.test.js.snap
src/settings/BatchGroupConfigurationSettings/__snapshots__/BatchGroupConfigurationForm.test.js.snap
src/settings/adjustments/SettingsAdjustmentsList/__snapshots__/SettingsAdjustmentsList.test.js.snap
src/settings/adjustments/SettingsAdjustmentsView/__snapshots__/SettingsAdjustmentsView.test.js.snap

test snapshots update

---

CHANGELOG.md
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLines.js
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLinesContainer.js
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLinesContainer.test.js
src/invoices/InvoiceDetails/InvoiceLines/__snapshots__/InvoiceLines.test.js.snap
src/invoices/InvoiceLineDetails/InvoiceLineDetailsContainer.js

https://issues.folio.org/browse/UINV-347 …

UINV-347 When clicking back from invoice line take user back to that row in invoice line table

---

CHANGELOG.md
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLines.js
src/invoices/InvoiceDetails/InvoiceLines/__snapshots__/InvoiceLines.test.js.snap

https://issues.folio.org/browse/UINV-350 …

UINV-350 'Undefined' displayed for receipt status and payment status if Invoice Line was created without POL

---

CHANGELOG.md
src/invoices/InvoiceDetails/Information/Information.js
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/PrintVoucher/ComponentToPrint/ComponentToPrint.js
src/invoices/Voucher/VoucherDetails.js

https://issues.folio.org/browse/UINV-351 …

UINV-351 Adding tenant's timezone in UI

---

CHANGELOG.md
src/settings/BatchGroupConfigurationSettings/BatchGroupConfigurationForm.js
src/settings/adjustments/SettingsAdjustmentsList/SettingsAdjustmentsList.js

https://issues.folio.org/browse/UINV-344 …

UINV-344 Settings > Invoices > change focus

---

CHANGELOG.md
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-354 …

UINV-354 A message of successful export is displayed after failing export

---

CHANGELOG.md
src/invoices/InvoiceDetails/utils.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-357 …

UINV-357 Invoice: Error message does not indicate what Fund does not have money

---

src/common/components/ApprovedBy/__snapshots__/ApprovedBy.test.js.snap
src/invoices/InvoiceDetails/InvoiceLines/__snapshots__/InvoiceLines.test.js.snap
src/invoices/InvoiceForm/__snapshots__/InvoiceForm.test.js.snap
src/invoices/InvoiceLineDetails/__snapshots__/InvoiceLineInformation.test.js.snap
src/invoices/InvoiceLineForm/__snapshots__/InvoiceLineForm.test.js.snap
src/invoices/InvoicesList/InvoicesListFilters/__snapshots__/InvoicesListFilters.test.js.snap
src/invoices/PrintVoucher/ComponentToPrint/__snapshots__/ComponentToPrint.test.js.snap
src/invoices/Voucher/__snapshots__/VoucherLinesDetails.test.js.snap
src/settings/adjustments/SettingsAdjustmentsView/__snapshots__/SettingsAdjustmentsView.test.js.snap

Snapshots updates

---

src/common/components/ApprovedBy/ApprovedBy.test.js
src/common/components/ApprovedBy/__snapshots__/ApprovedBy.test.js.snap
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceDetails/InvoiceDetails.test.js
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLines.test.js
src/invoices/InvoiceDetails/InvoiceLines/__snapshots__/InvoiceLines.test.js.snap
src/invoices/InvoiceDetails/VoucherInformation/VoucherInformation.test.js
src/invoices/InvoiceDetails/__snapshots__/InvoiceDetails.test.js.snap
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoiceForm/InvoiceForm.test.js
src/invoices/InvoiceForm/__snapshots__/InvoiceForm.test.js.snap
src/invoices/InvoiceLineDetails/InvoiceLineDetails.js
src/invoices/InvoiceLineDetails/InvoiceLineDetails.test.js
src/invoices/InvoiceLineDetails/InvoiceLineInformation.test.js
src/invoices/InvoiceLineDetails/__snapshots__/InvoiceLineDetails.test.js.snap
src/invoices/InvoiceLineDetails/__snapshots__/InvoiceLineInformation.test.js.snap
src/invoices/InvoiceLineForm/InvoiceLineForm.js
src/invoices/InvoiceLineForm/InvoiceLineForm.test.js
src/invoices/InvoiceLineForm/__snapshots__/InvoiceLineForm.test.js.snap
src/invoices/InvoicesList/InvoicesListFilters/InvoicesListFilters.js
src/invoices/InvoicesList/InvoicesListFilters/InvoicesListFilters.test.js
src/invoices/InvoicesList/InvoicesListFilters/__snapshots__/InvoicesListFilters.test.js.snap
src/invoices/InvoicesList/InvoicesListLastMenu.test.js
src/invoices/PrintVoucher/ComponentToPrint/ComponentToPrint.test.js
src/invoices/PrintVoucher/ComponentToPrint/__snapshots__/ComponentToPrint.test.js.snap
src/invoices/Voucher/VoucherLinesDetails.test.js
src/invoices/Voucher/__snapshots__/VoucherLinesDetails.test.js.snap
test/jest/__mock__/index.js
test/jest/__mock__/stripesComponents.mock.js

Fix test snapshots

---

src/invoices/InvoiceForm/InvoiceForm.test.js
src/invoices/InvoiceForm/__snapshots__/InvoiceForm.test.js.snap
src/invoices/InvoiceLineDetails/InvoiceLineInformation.test.js
src/invoices/InvoiceLineDetails/__snapshots__/InvoiceLineInformation.test.js.snap
src/invoices/InvoiceLineForm/InvoiceLineForm.test.js
src/invoices/InvoiceLineForm/__snapshots__/InvoiceLineForm.test.js.snap
src/settings/adjustments/SettingsAdjustmentsView/SettingsAdjustmentsView.test.js
src/settings/adjustments/SettingsAdjustmentsView/__snapshots__/SettingsAdjustmentsView.test.js.snap

snapshot updates

---

CHANGELOG.md
package.json
src/invoices/AdjustmentsDetails/__snapshots__/AdjustmentsDetails.test.js.snap
src/invoices/InvoiceDetails/DocumentsDetails/__snapshots__/DocumentsDetails.test.js.snap
src/invoices/InvoiceDetails/InvoiceLines/__snapshots__/InvoiceLines.test.js.snap
src/invoices/InvoiceDetails/VoucherInformation/__snapshots__/VoucherInformation.test.js.snap
src/invoices/InvoiceForm/__snapshots__/InvoiceForm.test.js.snap
src/invoices/InvoiceLineForm/__snapshots__/InvoiceLineForm.test.js.snap
src/invoices/InvoicesList/InvoicesListFilters/__snapshots__/InvoicesListFilters.test.js.snap
src/invoices/Voucher/VoucherEditForm/__snapshots__/VoucherEditForm.test.js.snap
src/invoices/Voucher/__snapshots__/VoucherLinesDetails.test.js.snap

https://issues.folio.org/browse/UINV-362 …

UINV-362 Un hide permission 'Invoice: Cancel invoices'

---

CHANGELOG.md
src/invoices/InvoiceDetails/InvoiceDetailsContainer.js

https://issues.folio.org/browse/UINV-372 …

UINV-372 Previous invoice is fetched when Approve and Pay action is called

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/UINV-379 …

UINV-379 release v3.1.1

---

CHANGELOG.md
src/invoices/AdjustmentsForm/__snapshots__/AdjustmentsForm.test.js.snap
src/invoices/InvoiceForm/__snapshots__/InvoiceForm.test.js.snap
src/invoices/InvoiceLineForm/__snapshots__/InvoiceLineForm.test.js.snap
src/invoices/InvoicesList/InvoicesListFilters/InvoicesListFilters.js
src/invoices/InvoicesList/InvoicesListFilters/__snapshots__/InvoicesListFilters.test.js.snap
src/invoices/InvoicesList/constants.js
src/invoices/InvoicesList/hooks/useBuildQuery/useBuildQuery.js
src/invoices/Voucher/VoucherEditForm/__snapshots__/VoucherEditForm.test.js.snap
src/invoices/Voucher/__snapshots__/VoucherViewLayer.test.js.snap
src/settings/adjustments/SettingsAdjustmentsView/__snapshots__/SettingsAdjustmentsView.test.js.snap

https://issues.folio.org/browse/UINV-366 …

UINV-366 Allow user to filter invoices by Lock total amount range

---

CHANGELOG.md
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLinesActions.js

https://issues.folio.org/browse/UINV-374 …

UINV-374 On small screens the action menu is covered by the header

---

CHANGELOG.md
package.json
src/invoices/Invoices.js
src/invoices/InvoicesList/InvoicesList.js
src/invoices/InvoicesList/InvoicesListLastMenu.js
src/invoices/InvoicesList/__snapshots__/InvoicesListLastMenu.test.js.snap
src/invoices/VoucherExport/VoucherExport.js
src/invoices/VoucherExport/VoucherExport.test.js
src/invoices/VoucherExport/__snapshots__/VoucherExport.test.js.snap
src/invoices/VoucherExport/index.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-368
tests for `Voucher export` page will be added with next story (https://issues.folio.org/browse/UINV-369)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number …

UINV-368 Add "Voucher export" to actions menu

---

CHANGELOG.md
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceDetails/__snapshots__/InvoiceDetails.test.js.snap
src/invoices/InvoiceLineDetails/OtherRelatedInvoiceLines/OtherRelatedInvoiceLines.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-390
https://issues.folio.org/browse/UINV-391
While it's …

UINV-390 UINV-391 Remove "Folio invoice number" from invoice line column. Update accordion labels and logic on Invoice

---

src/invoices/InvoicesList/ExportSettingsModal/ExportSettingsModal.js
src/invoices/InvoicesList/ExportSettingsModal/utils/createExportReport.js
src/invoices/InvoicesList/ExportSettingsModal/utils/createExportReport.test.js
src/invoices/InvoicesList/ExportSettingsModal/utils/getExportData.js
test/jest/fixtures/exportReport.js

https://issues.folio.org/browse/UINV-385?focusedCommentId=128950&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-128950 …

UINV-385 Add exchange rate to export file

---

src/invoices/InvoicesList/ExportSettingsModal/utils/createExportReport.test.js
src/invoices/InvoicesList/ExportSettingsModal/utils/getExportData.js

UINV-385 fix exchange rate

---

.eslintrc
CHANGELOG.md
package.json
src/invoices/InvoicesList/ExportSettingsModal/utils/getExportData.js
src/invoices/InvoicesList/InvoicesListFilters/__snapshots__/InvoicesListFilters.test.js.snap

https://issues.folio.org/browse/UINV-393 …

UINV-393 replace babel-eslint with @babel/eslint-parser

---

CHANGELOG.md
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLines.js
src/invoices/InvoiceDetails/InvoiceLines/__snapshots__/InvoiceLines.test.js.snap

https://issues.folio.org/browse/UINV-283 …

UINV-283 Additional sort options for invoice lines

---

CHANGELOG.md
src/invoices/InvoiceDetails/InvoiceDetailsContainer.js
src/invoices/InvoiceDetails/InvoiceDetailsContainer.test.js
src/invoices/InvoiceDetails/utils.js
src/invoices/InvoiceDetails/utils.test.js
src/invoices/InvoiceLineForm/InvoiceLineFormContainer.js
src/invoices/InvoiceLineForm/InvoiceLineFormContainer.test.js
translations/ui-invoice/en.json

UINV-398 Error handling for adding invoice line

---

CHANGELOG.md
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLineOrderLineLink/InvoiceLineOrderLineLink.js
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLineOrderLineNumber/InvoiceLineOrderLineNumber.js
src/invoices/Voucher/VoucherEditForm/VoucherEditForm.js
src/invoices/Voucher/VoucherEditForm/VoucherEditForm.test.js
src/invoices/Voucher/VoucherEditForm/__snapshots__/VoucherEditForm.test.js.snap
src/settings/adjustments/SettingsAdjustmentsView/SettingsAdjustmentsViewContainer.js
src/settings/adjustments/SettingsAdjustmentsView/SettingsAdjustmentsViewContainer.test.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-404 …

UINV-404 module warnings analysis

---

CHANGELOG.md
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLineOrderLineNumber/InvoiceLineOrderLineNumber.js
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLineOrderLineNumber/InvoiceLineOrderLineNumber.test.js
src/invoices/InvoiceDetails/VendorDetails/VendorDetails.js
src/invoices/InvoiceDetails/VendorDetails/__snapshots__/VendorDetails.test.js.snap
src/invoices/InvoiceLineDetails/InvoiceLineInformation.js
src/invoices/InvoiceLineDetails/OtherRelatedInvoiceLines/OtherRelatedInvoiceLines.js
src/invoices/InvoiceLineDetails/__snapshots__/InvoiceLineInformation.test.js.snap
src/settings/BatchGroupConfigurationSettings/__snapshots__/BatchGroupConfigurationForm.test.js.snap

https://issues.folio.org/browse/UINV-403 …

UINV-403 Add copy icon to invoice number

---

src/invoices/InvoiceDetails/InvoiceDetailsContainer.js

UINV-398 fix error message

---

CHANGELOG.md
src/invoices/PrintVoucher/ComponentToPrint/ComponentToPrint.js
src/invoices/PrintVoucher/ComponentToPrint/__snapshots__/ComponentToPrint.test.js.snap
src/invoices/PrintVoucher/utils.js

https://issues.folio.org/browse/UINV-399 …

UINV-399 Allow user to print voucher in landscape or portrait orientation

---

CHANGELOG.md
src/common/constants/constants.js
src/invoices/InvoiceDetails/utils.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-418 …

UINV-418 Error handling for approving invoice

---

CHANGELOG.md
src/common/constants/constants.js
src/common/hooks/index.js
src/common/hooks/useOrderLines/index.js
src/common/hooks/useOrderLines/useOrderLines.js
src/common/hooks/useOrderLines/useOrderLines.test.js
src/common/hooks/useOrders/index.js
src/common/hooks/useOrders/useOrders.js
src/common/hooks/useOrders/useOrders.test.js
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoiceForm/InvoiceFormContainer.js
src/invoices/InvoiceForm/InvoiceFormContainer.test.js
src/settings/BatchGroupConfigurationSettings/__snapshots__/BatchGroupConfigurationForm.test.js.snap
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-420 …

UINV-420 Create new invoice from order

---

CHANGELOG.md
package.json
src/common/hooks/index.js
src/common/hooks/useVendors/index.js
src/common/hooks/useVendors/useVendors.js
src/common/hooks/useVendors/useVendors.test.js
src/invoices/InvoiceForm/InvoiceFormContainer.js
src/invoices/InvoiceLinesSequence/InvoiceLinesSequence.js
src/invoices/InvoiceLinesSequence/InvoiceLinesSequenceContainer.js
src/invoices/InvoiceLinesSequence/index.js
src/invoices/InvoiceLinesSequence/useLinesSequence.js
src/invoices/Invoices.js
src/invoices/utils.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-421 …

UINV-421 Edit sequence of invoice lines

---

src/invoices/InvoiceForm/InvoiceFormContainer.js

UINV-420 handle cancel button click

---

CHANGELOG.md
package.json
src/settings/BatchGroupConfigurationSettings/__snapshots__/BatchGroupConfigurationForm.test.js.snap

https://issues.folio.org/browse/UINV-414 …

Release v3.2.0

---

CHANGELOG.md
package.json
src/invoices/InvoiceLineForm/__snapshots__/InvoiceLineForm.test.js.snap

https://issues.folio.org/browse/UINV-429 …

Release v3.2.1

---

CHANGELOG.md
src/invoices/InvoiceDetails/InvoiceActions/InvoiceActions.js
src/invoices/InvoiceDetails/InvoiceActions/InvoiceActions.test.js

https://issues.folio.org/browse/UINV-426 …

UINV-426 Add icons for invoice actions

---

CHANGELOG.md
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoicesList/InvoicesList.js

https://issues.folio.org/browse/UINV-427 …

UINV-427 Display Vendor code

---

CHANGELOG.md
src/invoices/AdjustmentsForm/AdjustmentsForm.js
src/settings/adjustments/SettingsAdjustmentsEditor/SettingsAdjustmentsEditor.js

https://issues.folio.org/browse/UINV-433 …

UINV-433 Disable select 'Separate from'

---

CHANGELOG.md
package.json
src/common/constants/api.js
src/common/hooks/index.js
src/common/hooks/useFundDistributionValidation/index.js
src/common/hooks/useFundDistributionValidation/useFundDistributionValidation.js
src/common/hooks/useFundDistributionValidation/useFundDistributionValidation.test.js
src/invoices/AdjustmentsForm/AdjustmentsForm.js
src/invoices/InvoiceLineForm/InvoiceLineForm.js
src/invoices/InvoiceLineForm/InvoiceLineForm.test.js

https://issues.folio.org/browse/UINV-432 …

UINV-432 Fund validation

---

CHANGELOG.md
src/common/constants/constants.js
src/common/hooks/index.js
src/common/hooks/useOrderLines/index.js
src/common/hooks/useOrderLines/useOrderLines.js
src/common/hooks/useOrderLines/useOrderLines.test.js
src/common/hooks/useOrders/index.js
src/common/hooks/useOrders/useOrders.js
src/common/hooks/useOrders/useOrders.test.js
src/common/hooks/useVendors/index.js
src/common/hooks/useVendors/useVendors.js
src/common/hooks/useVendors/useVendors.test.js
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoiceForm/InvoiceFormContainer.js
src/invoices/InvoiceForm/InvoiceFormContainer.test.js
src/invoices/InvoiceLinesSequence/InvoiceLinesSequence.js
src/invoices/InvoiceLinesSequence/InvoiceLinesSequenceContainer.js
src/invoices/InvoiceLinesSequence/index.js
src/invoices/InvoiceLinesSequence/useLinesSequence.js
src/invoices/Invoices.js
src/invoices/utils.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-420
https://issues.folio.org/browse/UINV-421
Merge implemented features (Nolana) from `dev` to `master`.
Related PRs:
https://github.com/folio-org/ui-invoice/pull/609
https://github.com/folio-org/ui-invoice/pull/611
https://github.com/folio-org/ui-invoice/pull/613
https://github.com/folio-org/ui-invoice/pull/610
https://github.com/folio-org/ui-invoice/pull/612
- Are the JIRAs under active …

Merge implemented features from Nolana

---

CHANGELOG.md
package.json
src/settings/BatchGroupsSettings/BatchGroupsSettings.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-438 …

UINV-438 Provide local translations to `ControlledVocab`

---

CHANGELOG.md
package.json
src/invoices/AdjustmentsForm/__snapshots__/AdjustmentsForm.test.js.snap
src/invoices/InvoiceDetails/__snapshots__/InvoiceDetails.test.js.snap
src/invoices/InvoiceForm/__snapshots__/InvoiceForm.test.js.snap
src/invoices/InvoiceLineDetails/__snapshots__/InvoiceLineDetails.test.js.snap
src/invoices/InvoiceLineForm/__snapshots__/InvoiceLineForm.test.js.snap
src/invoices/InvoicesList/InvoicesListFilters/__snapshots__/InvoicesListFilters.test.js.snap
src/settings/BatchGroupConfigurationSettings/__snapshots__/BatchGroupConfigurationForm.test.js.snap

https://issues.folio.org/browse/UINV-455 …

UINV-455 bump stripes to 8.0.0 for Orchid/2023-R1

---

src/invoices/AdjustmentsDetails/__snapshots__/AdjustmentsDetails.test.js.snap
src/invoices/InvoiceDetails/DocumentsDetails/__snapshots__/DocumentsDetails.test.js.snap
src/invoices/InvoiceDetails/InvoiceLines/__snapshots__/InvoiceLines.test.js.snap

Update jest snapshots

---

CHANGELOG.md
src/invoices/InvoiceDetails/InvoiceActions/InvoiceActions.js
src/invoices/InvoiceDetails/InvoiceActions/InvoiceActions.test.js
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceDetails/InvoiceDetails.test.js
src/invoices/InvoiceDetails/constants.js
translations/ui-invoice/en.json

[UINV-467](https://issues.folio.org/browse/UINV-467) - show warning message and disable **Approve & Pay** button if the vendor status eqault to `Inactive`
- display the warning message "Vendor is inactive. Invoice cannot be approved or paid."
- disable "Approve & Pay" button if `vendor.status === "Inactive"`
Ideally all of the PRs involved in breaking …

UINV-467 Disable ability to approve & pay invoice against inactive organization

---

package.json
src/invoices/AdjustmentsDetails/__snapshots__/AdjustmentsDetails.test.js.snap
src/invoices/InvoiceDetails/DocumentsDetails/__snapshots__/DocumentsDetails.test.js.snap
src/invoices/InvoiceDetails/InvoiceLines/__snapshots__/InvoiceLines.test.js.snap
src/invoices/InvoiceDetails/VoucherInformation/__snapshots__/VoucherInformation.test.js.snap
src/invoices/InvoiceLineDetails/__snapshots__/InvoiceLineInformation.test.js.snap
src/invoices/Voucher/__snapshots__/VoucherLinesDetails.test.js.snap

missed setting permissions

---

CHANGELOG.md
src/common/components/FieldFiscalYear/FieldFiscalYear.js
src/common/components/FieldFiscalYear/FieldFiscalYearContainer.js
src/common/components/FieldFiscalYear/FieldFiscalYearContainer.test.js
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoiceForm/InvoiceForm.test.js

[UINV-481](https://issues.folio.org/browse/UINV-481) - Prevent resetting fiscalYearId
- add `required` filed for Fiscal Year input on `editMode` if there was a `fiscalYearId` previously …

UINV-481 - Prevent resetting fiscalYearId

---

CHANGELOG.md
src/invoices/InvoiceLineForm/InvoiceLineFormContainer.js

https://issues.folio.org/browse/UINV-484
Set form init value for the field.
While it's …

UINV-484 'Release encumbrance' checkbox becomes checked after adding new blank invoice line

---

CHANGELOG.md
package.json
src/invoices/AdjustmentsForm/AdjustmentsForm.js
src/invoices/AdjustmentsForm/AdjustmentsForm.test.js
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoiceLineForm/InvoiceLineForm.js

[UINV-479](https://issues.folio.org/browse/UINV-479) - Allow user to select Fund and Expense class from Fiscal year specified in invoice.
- pass `fiscalYearId` for `FundDistributionFieldsFinalContainer` component of `@folio/stripes-acq-components` module
[Video source](https://epam-my.sharepoint.com/:v:/p/alisher_musurmonov1/EYXZQrxtsfBKkqCHn8SqBr8BjcKBT_FoGAre9VVkdpH3dg?e=3RmFyT)
- Do PRs …

UINV-479 - get expanse classes with fiscalYearId

---

CHANGELOG.md
src/common/utils/getAccountingCodeOptions/getAccountingCodeOptions.js
src/common/utils/getAccountingCodeOptions/getAccountingCodeOptions.test.js
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoiceForm/InvoiceForm.test.js
translations/ui-invoice/en.json

https://issues.folio.org/browse/UINV-489 …

UINV-489 The value 'Default' is hard-coded instead of localized

---

src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoiceForm/InvoiceFormContainer.js

UINV-491 Invoice adjustments select list is empty

---

CHANGELOG.md
src/common/constants/constants.js
src/invoices/InvoiceDetails/utils.js
src/invoices/InvoiceDetails/utils.test.js
translations/ui-invoice/en.json

[UINV-497](https://issues.folio.org/browse/UINV-497)- Add handling for a new error code that occurs during invoice approval
- add  `incorrectFundDistributionTotal` error code message for the error handling map.
https://github.com/folio-org/ui-invoice/assets/116072773/6c4c1e63-7505-4bec-aea0-ebe8a5158996
Ideally all of the PRs involved in breaking changes …

UINV-497: add new error error code for approving an invoice

---

translations/ui-invoice/en.json

[UINV-497](https://issues.folio.org/browse/UINV-497) - Update text message
While it's …

UINV-497: update error message text.

---

translations/ui-invoice/en.json

Jira issue [UINV-497](https://issues.folio.org/browse/UINV-497)
- Fix grammar issue of the error message. …

UINV-497: fix grammar issue of error message

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/UINV-502
Add the following permissions as sub permissions for `ui-invoice.exportCSV`:
- `batch-groups.collection.get`
- `finance.exchange-rate.item.get` …

UINV-502 Add required sub permissions to perform export of search results

---

CHANGELOG.md
src/invoices/AdjustmentsDetails/__snapshots__/AdjustmentsDetails.test.js.snap
src/invoices/InvoiceDetails/DocumentsDetails/__snapshots__/DocumentsDetails.test.js.snap
src/invoices/InvoiceDetails/InvoiceLines/__snapshots__/InvoiceLines.test.js.snap
src/invoices/InvoiceDetails/VoucherInformation/__snapshots__/VoucherInformation.test.js.snap
src/invoices/InvoiceLineDetails/OtherRelatedInvoiceLines/OtherRelatedInvoiceLines.js
src/invoices/InvoiceLineDetails/__snapshots__/InvoiceLineInformation.test.js.snap
src/invoices/Voucher/__snapshots__/VoucherLinesDetails.test.js.snap

Correctly import `DESC_DIRECTION` in `OtherRelatedInvoiceLines.js` from `@folio/stripes-acq-components`, where it exists, instead of from `@folio/stripes/components`, where it does not.
Refs [UINV-507](https://issues.folio.org/browse/UINV-507)

UINV-507 correctly import DESC_DIRECTION

---

src/invoices/InvoiceLineForm/InvoiceLineForm.js
src/invoices/utils.js
src/invoices/utils.test.js
translations/ui-invoice/en.json

[UINV-498](https://issues.folio.org/browse/UINV-498) - add inactive status for account numbers
https://github.com/folio-org/ui-invoice/assets/116072773/51b7d112-885a-401a-81f0-5cbc97978910
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that …

UINV-498: add inactive status for account numbers

---

CHANGELOG.md
src/common/constants/constants.js
src/invoices/InvoiceDetails/utils.js
src/invoices/InvoiceDetails/utils.test.js
translations/ui-invoice/en.json

[UINV-513](https://issues.folio.org/browse/UINV-513) - Error Message - Invoice cancellation allowed against closed budget
https://github.com/folio-org/ui-invoice/assets/116072773/9a085d54-93cd-45dc-b60b-7dc731971c32 …

UINV-513: add error message to prevent invoice cancellation

---

CHANGELOG.md
src/invoices/InvoicesList/constants.js
src/invoices/InvoicesList/hooks/useBuildQuery/useBuildQuery.js
src/invoices/InvoicesList/hooks/useBuildQuery/useBuildQuery.test.js

[UINV-510](https://issues.folio.org/browse/UINV-510) - Not able to filter with tags that are entirely made of special characters.
https://github.com/folio-org/ui-invoice/assets/116072773/70435d8b-828f-404c-926d-12b8ea7b9246 …

UINV-510: fix filtering via tags created using special characters

---

CHANGELOG.md
src/invoices/InvoicesList/ExportSettingsModal/utils/createExportReport.js
src/invoices/InvoicesList/ExportSettingsModal/utils/createExportReport.test.js
test/jest/fixtures/exportReport.js

https://issues.folio.org/browse/UINV-515
In the export line, the external account number is displayed only for the first voucher line found. This field must include all numbers associated with the invoice (invoice voucher).
Collect external account numbers from all associated voucher lines.
https://github.com/folio-org/ui-invoice/assets/88109087/f1f1328c-237c-439c-8b74-0e399d7a8af5
- Do …

UINV-515 Display all external account numbers associated with an invoice in the export report (CSV)

---

CHANGELOG.md
src/common/constants/constants.js
src/invoices/InvoiceDetails/utils.js
src/invoices/InvoiceDetails/utils.test.js
translations/ui-invoice/en.json

[UINV-518](https://issues.folio.org/browse/UINV-518) - Support error message Uninformative error in invoice payment due to user not linked to the Purchase Order's acquisition unit.
https://github.com/folio-org/ui-invoice/assets/116072773/54266905-c6e1-4b5f-be7b-cde57b8898b9
Ideally all of the PRs involved in breaking changes would be merged in the same day …

UINV-518: support new error message

---

src/invoices/InvoiceForm/__snapshots__/InvoiceForm.test.js.snap
src/invoices/InvoicesList/ExportSettingsModal/utils/createExportReport.js
src/invoices/InvoicesList/ExportSettingsModal/utils/createExportReport.test.js
src/invoices/InvoicesList/ExportSettingsModal/utils/getExportData.js
test/jest/__mock__/index.js
test/jest/__mock__/resizeObserver.mock.js

https://issues.folio.org/browse/UINV-515?focusedCommentId=199986&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-199986
"External account number" column should contain only invoice line fund distribution's related external account numbers.
original PR - https://github.com/folio-org/ui-invoice/pull/745
Fetch funds by IDs and map external account numbers with invoice line fund distributions.
https://github.com/folio-org/ui-invoice/assets/88109087/e9c49016-4006-4a5d-8a6d-6944c03a4b5e
- What other …

UINV-515 Align external account numbers with invoice line fund distributions in CSV report

---

src/invoices/InvoicesList/ExportSettingsModal/utils/createExportReport.js
src/invoices/InvoicesList/ExportSettingsModal/utils/createExportReport.test.js
src/invoices/InvoicesList/ExportSettingsModal/utils/getExportData.js
test/jest/__mock__/index.js
test/jest/__mock__/resizeObserver.mock.js

Propagate changes from develop branch
https://github.com/folio-org/ui-invoice/pull/748

Sprint 182 - UINV-515

---

CHANGELOG.md
package.json
src/invoices/InvoiceLineDetails/ReceivingHistory/ReceivingHistory.js
src/invoices/InvoiceLineDetails/ReceivingHistory/ReceivingHistory.test.js
translations/ui-invoice/en.json

[UINV-529](https://issues.folio.org/browse/UINV-529) - UINV-529: add changed filed name from `caption` to `displaySummary` …

UINV-529: add changed filed name from `caption` to `displaySummary`

---

CHANGELOG.md
src/invoices/InvoiceLineDetails/OtherRelatedInvoiceLines/OtherRelatedInvoiceLines.js

UINV-534 Invoice line Subscription fields are not populated correctly on Invoice line pane

---

CHANGELOG.md
package.json
src/common/components/CalculatedExchangeAmount/CalculatedExchangeAmount.js
src/common/components/CalculatedExchangeAmount/CalculatedExchangeAmount.test.js
src/common/components/CalculatedExchangeAmount/index.js
src/common/components/index.js
src/common/constants/api.js
src/common/hooks/index.js
src/common/hooks/useExchangeCalculation/index.js
src/common/hooks/useExchangeCalculation/useExchangeCalculation.js
src/common/hooks/useExchangeCalculation/useExchangeCalculation.test.js
src/invoices/InvoiceDetails/Information/Information.js
src/invoices/InvoiceDetails/Information/Information.test.js
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceDetails/__snapshots__/InvoiceDetails.test.js.snap
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoiceForm/InvoiceForm.test.js
src/invoices/InvoiceForm/InvoiceFormContainer.js
src/invoices/InvoiceForm/__snapshots__/InvoiceForm.test.js.snap
src/invoices/InvoiceLineForm/InvoiceLineForm.test.js
src/invoices/InvoiceLineForm/__snapshots__/InvoiceLineForm.test.js.snap
src/invoices/InvoicesList/InvoicesListFilters/__snapshots__/InvoicesListFilters.test.js.snap
translations/ui-invoice/en.json

https://folio-org.atlassian.net/browse/UINV-530
https://folio-org.atlassian.net/browse/UINV-522

Sprint 184 - UINV-522, UINV-530

---

CHANGELOG.md
src/invoices/InvoiceDetails/ApproveConfirmationModal/ApproveConfirmationModal.js
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceDetails/InvoiceDetails.test.js

[UINV-521](https://folio-org.atlassian.net/browse/UINV-521): display duplicate warning when approving and paying an invoice
https://github.com/folio-org/ui-invoice/assets/116072773/f0a318e7-c676-4acb-a359-717724fbff67 …

UINV-521: display duplicate warning when approving and paying an invoice

---

CHANGELOG.md
src/invoices/InvoiceLineForm/InvoiceLineForm.js
src/invoices/InvoiceLineForm/__snapshots__/InvoiceLineForm.test.js.snap

https://folio-org.atlassian.net/browse/UINV-533
User can leave "Account number" field empty in invoice line when related vendor has only one account number.
Eliminate the logic that renders the field non-interactive when only one account is available.
https://github.com/folio-org/ui-invoice/assets/88109087/f28907e3-5089-4e32-8ad2-4dca1e302fe1
Ideally all …

UINV-533 Enable interaction for the 'Account Number' field in the invoice line form when it contains only one account

---

CHANGELOG.md
src/invoices/InvoiceDetails/ApproveConfirmationModal/ApproveConfirmationModal.js
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceDetails/InvoiceDetails.test.js
src/invoices/InvoiceLineForm/InvoiceLineForm.js
src/invoices/InvoiceLineForm/__snapshots__/InvoiceLineForm.test.js.snap

https://folio-org.atlassian.net/browse/UINV-521
https://folio-org.atlassian.net/browse/UINV-533

Sprint 185 - UINV-521, UINV-533

---

CHANGELOG.md
src/invoices/InvoiceForm/__snapshots__/InvoiceForm.test.js.snap
src/invoices/InvoiceLineForm/__snapshots__/InvoiceLineForm.test.js.snap
src/invoices/InvoicesList/InvoicesList.js
src/invoices/InvoicesList/InvoicesListFilters/__snapshots__/InvoicesListFilters.test.js.snap
translations/ui-invoice/en.json

https://folio-org.atlassian.net/browse/UINV-523
https://github.com/folio-org/ui-invoice/assets/88109087/210304cb-1e02-407a-9c18-f332003fa102 …

UINV-523 UX Consistency > Search results > Update HTML page title with search term entered

---

CHANGELOG.md
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoiceForm/InvoiceFormContainer.js

[UINV-539](https://folio-org.atlassian.net/browse/UINV-539) - Fix new invoice creation workflow with POL currency overwritten by Vendor currency.
https://github.com/folio-org/ui-invoice/assets/116072773/b41381fa-d97d-4f69-88bb-d5c63b3294e3
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …

UINV-539: Fix new invoice creation workflow with POL currency overwritten by Vendor currency

---

CHANGELOG.md
package.json

https://folio-org.atlassian.net/browse/UINV-545

UINV-545 Align the 'finance.fund' interface version (3.0)

---

CHANGELOG.md
package.json

Release v6.0.2

---

src/invoices/InvoiceDetails/InvoiceLines/AddInvoiceLinesAction.js
src/invoices/InvoiceDetails/InvoiceLines/AddInvoiceLinesAction.test.js
src/invoices/InvoiceDetails/InvoiceLines/AddInvoiceLinesActionContainer.js
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLinesActions.js
src/invoices/InvoiceDetails/InvoiceLines/InvoiceLinesActions.test.js

UINV-543 do not close po line plugin on focus change

---

CHANGELOG.md
package.json
src/invoices/InvoiceDetails/InvoiceLines/AddInvoiceLinesActionContainer.js

Release v6.0.3

---

CHANGELOG.md
src/invoices/InvoiceDetails/InvoiceLines/hooks/useInvoiceOrders/useInvoiceOrders.js

[UINV-546](https://folio-org.atlassian.net/browse/UINV-546): Add indexes to improve the performance of getting composite orders by poNumber …

UINV-546: Add indexes to improve the performance of getting composite orders by poNumber

---

CHANGELOG.md
src/common/components/FieldFiscalYear/FieldFiscalYearContainer.test.js
src/common/hooks/useInvoiceLineMutation/useInvoiceLineMutation.js
src/common/hooks/useInvoiceLineMutation/useInvoiceLineMutation.test.js
src/common/hooks/useInvoiceMutation/useInvoiceMutation.js
src/common/hooks/useInvoiceMutation/useInvoiceMutation.test.js
src/invoices/AdjustmentsForm/__snapshots__/AdjustmentsForm.test.js.snap
src/invoices/InvoiceDetails/Information/Information.test.js
src/invoices/InvoiceDetails/InvoiceActions/InvoiceActions.js
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceDetails/InvoiceDetails.test.js
src/invoices/InvoiceDetails/InvoiceDetailsContainer.js
src/invoices/InvoiceDetails/InvoiceDetailsContainer.test.js
src/invoices/InvoiceDetails/utils.js
src/invoices/InvoiceDetails/utils.test.js
src/invoices/InvoiceForm/InvoiceForm.test.js
src/invoices/InvoiceForm/__snapshots__/InvoiceForm.test.js.snap
src/invoices/InvoiceLineForm/__snapshots__/InvoiceLineForm.test.js.snap
src/invoices/InvoicesList/ExportSettingsModal/ExportSettingsModal.test.js
src/invoices/InvoicesList/InvoicesListFilters/InvoicesListFilters.test.js
src/invoices/InvoicesList/InvoicesListFilters/__snapshots__/InvoicesListFilters.test.js.snap
translations/ui-invoice/en.json

[UINV-552](https://folio-org.atlassian.net/browse/UINV-552): Duplicate invoice and invoice lines
- We will duplicate an invoice with an invoice to create permissions. The status must be "Open" and let BE handle the current fiscal year based on invoice line creation
- Invoice lines are also duplicated one by one making create invoice line requests.
https://github.com/user-attachments/assets/fecadb90-b1e5-459a-95d2-d65d99f00fb8
- …

UINV-552: Duplicate invoice and invoice lines

---

src/invoices/InvoiceDetails/InvoiceDetailsContainer.js
src/invoices/InvoiceDetails/constants.js
src/invoices/InvoiceDetails/utils.test.js
src/invoices/InvoicesList/InvoicesListFilters/InvoicesListFilters.test.js
src/invoices/InvoicesList/InvoicesListFilters/__snapshots__/InvoicesListFilters.test.js.snap

[UINV-552](https://folio-org.atlassian.net/browse/UINV-552): omit `approvalDate` and `approvedBy` fields
https://github.com/user-attachments/assets/8504a3a2-f69c-4023-8630-18da154382e7 …

UINV-552: omit `approvalDate` and `approvedBy` fields

---

CHANGELOG.md
src/invoices/InvoicesList/ExportSettingsModal/constants.js
src/invoices/InvoicesList/ExportSettingsModal/utils/createExportReport.js
src/invoices/InvoicesList/InvoicesListSearchConfig.js
translations/ui-invoice/en.json

https://folio-org.atlassian.net/browse/UINV-556 …

UINV-556 Add search index for and export Folio Invoice Number

---

src/common/hooks/useInvoiceLineMutation/useInvoiceLineMutation.js

UINV-552: make sequential requests to create invoice lines
https://github.com/user-attachments/assets/9048bc61-478d-4312-b572-7cb5e12235f6
https://github.com/user-attachments/assets/d4813e61-ef3b-4cb0-bb17-659018ccdeec …

UINV-552: make sequential requests to create invoice lines

---

package.json
src/invoices/AdjustmentsForm/__snapshots__/AdjustmentsForm.test.js.snap
src/invoices/InvoiceForm/__snapshots__/InvoiceForm.test.js.snap
src/invoices/InvoiceLineForm/__snapshots__/InvoiceLineForm.test.js.snap
src/invoices/InvoicesList/InvoicesListFilters/__snapshots__/InvoicesListFilters.test.js.snap
src/invoices/Voucher/VoucherEditForm/__snapshots__/VoucherEditForm.test.js.snap

UINV-552: update failing snapshot tests on `master` branch https://github.com/folio-org/ui-invoice/actions/runs/10449678848/job/28983674726 …

UINV-552: update failing snapshot tests

---

CHANGELOG.md
package.json

https://folio-org.atlassian.net/browse/UINV-556

Release v6.0.4

---

src/invoices/InvoiceDetails/constants.js
src/invoices/InvoiceDetails/utils.js

UINV-552: add missing `paymentDate` for the omitting invoice fields list and set invoice line status to `Open` on duplicate invoice. …

UINV-552: add missing `paymentDate` for the omitting invoice fields list and set invoice line status to `Open` on duplicate invoice

---

src/invoices/InvoiceDetails/utils/errorHandlers.js
src/invoices/InvoiceDetails/utils/utils.js

apply strategies pattern for some errors handling

---

CHANGELOG.md
package.json
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/Invoices.js
src/invoices/InvoicesList/InvoicesListLastMenu.js
translations/ui-invoice/en.json

UINV-559 Clean up permission names

---

package.json
src/invoices/AdjustmentsDetails/__snapshots__/AdjustmentsDetails.test.js.snap
src/invoices/AdjustmentsForm/AdjustmentsForm.test.js
src/invoices/InvoiceDetails/DocumentsDetails/__snapshots__/DocumentsDetails.test.js.snap
src/invoices/InvoiceDetails/InvoiceLines/__snapshots__/InvoiceLines.test.js.snap
src/invoices/InvoiceDetails/VoucherInformation/__snapshots__/VoucherInformation.test.js.snap
src/invoices/InvoiceDetails/__snapshots__/InvoiceDetails.test.js.snap
src/invoices/InvoiceForm/InvoiceForm.test.js
src/invoices/InvoiceForm/__snapshots__/InvoiceForm.test.js.snap
src/invoices/InvoiceLineDetails/__snapshots__/InvoiceLineInformation.test.js.snap
src/invoices/InvoiceLineForm/InvoiceLineForm.test.js
src/invoices/InvoiceLineForm/__snapshots__/InvoiceLineForm.test.js.snap
src/invoices/InvoicesList/InvoicesListFilters/InvoicesListFilters.test.js
src/invoices/InvoicesList/InvoicesListFilters/__snapshots__/InvoicesListFilters.test.js.snap
src/invoices/Voucher/__snapshots__/VoucherLinesDetails.test.js.snap
src/settings/BatchGroupConfigurationSettings/__snapshots__/BatchGroupConfigurationForm.test.js.snap

Update ACQ components version and jest snapshots

---

CHANGELOG.md
src/common/constants/constants.js
src/common/constants/index.js
src/common/constants/routes.js
src/invoices/AdjustmentsForm/AdjustmentsForm.test.js
src/invoices/AdjustmentsForm/__snapshots__/AdjustmentsForm.test.js.snap
src/invoices/InvoiceDetails/InvoiceDetails.js
src/invoices/InvoiceDetails/InvoiceDetails.test.js
src/invoices/InvoiceDetails/__snapshots__/InvoiceDetails.test.js.snap
src/invoices/InvoiceForm/InvoiceForm.test.js
src/invoices/InvoiceForm/__snapshots__/InvoiceForm.test.js.snap
src/invoices/InvoiceLineForm/InvoiceLineForm.test.js
src/invoices/InvoiceLineForm/__snapshots__/InvoiceLineForm.test.js.snap
src/invoices/Invoices.js
src/invoices/InvoicesList/InvoicesList.js
src/invoices/InvoicesList/InvoicesListFilters/InvoicesListFilters.test.js
src/invoices/InvoicesList/InvoicesListFilters/__snapshots__/InvoicesListFilters.test.js.snap
src/invoices/VersionHistory/VersionHistory.js
src/invoices/VersionHistory/index.js

[UINV-468](https://folio-org.atlassian.net/browse/UINV-468): Open version history pane on click change log icon
https://github.com/user-attachments/assets/c4570ea7-b37c-4b25-966a-10feb5cb672b
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …

UINV-468: Open version history pane on click change log icon

---

src/common/constants/routes.js

[UINV-566:](https://folio-org.atlassian.net/browse/UINV-566) add missing slash for the invoice voucher router reported here https://folio-org.atlassian.net/browse/UINV-566?focusedCommentId=239408
https://github.com/user-attachments/assets/4443ed1b-d6d4-4cd4-bc50-297929cf1734
Ideally all of the PRs involved in breaking changes would be merged in the same …

UINV-566: add missing slash for the invoice voucher router

---

package.json

Align ui-invoice.acq.unit.assignment.assign permission displayName

---

CHANGELOG.md
src/invoices/VersionHistory/InvoiceVersionHistory/VersionHistoryView/VersionHistoryView.js
src/invoices/VersionHistory/InvoiceVersionHistory/VersionHistoryView/VersionHistoryViewExtendedInformation/VersionHistoryViewExtendedInformation.js
src/invoices/VersionHistory/InvoiceVersionHistory/VersionHistoryView/VersionHistoryViewExtendedInformation/index.js
src/invoices/VersionHistory/InvoiceVersionHistory/VersionHistoryView/VersionHistoryViewVendorDetails/VersionHistoryViewVendorDetails.js
src/invoices/VersionHistory/InvoiceVersionHistory/VersionHistoryView/VersionHistoryViewVendorDetails/index.js
src/invoices/VersionHistory/constants.js

Display vendor details and extended info for version history …

UINV-569 Display vendor details and extended info for version history

---

CHANGELOG.md
package.json

UINV-576 add missed permissions

---

CHANGELOG.md
src/invoices/InvoicesList/InvoicesListFilters/InvoicesListFilters.js
src/invoices/InvoicesList/InvoicesListFilters/InvoicesListFilters.test.js
src/invoices/InvoicesList/InvoicesListFilters/__snapshots__/InvoicesListFilters.test.js.snap
src/invoices/InvoicesList/constants.js
src/invoices/InvoicesList/hooks/useBuildQuery/useBuildQuery.js
translations/ui-invoice/en.json

https://folio-org.atlassian.net/browse/UINV-341 …

UINV-341 Add Total Amount filter

---

CHANGELOG.md
src/common/constants/constants.js
src/common/hooks/useInvoice/useInvoice.js
src/common/hooks/useInvoiceLine/useInvoiceLine.js
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoiceForm/InvoiceForm.test.js
src/invoices/InvoiceForm/InvoiceFormContainer.js
src/invoices/InvoiceForm/InvoiceFormContainer.test.js
src/invoices/InvoiceForm/__snapshots__/InvoiceForm.test.js.snap
src/invoices/InvoiceLineForm/InvoiceLineForm.js
src/invoices/InvoiceLineForm/InvoiceLineFormContainer.js
src/invoices/InvoiceLineForm/InvoiceLineFormContainer.test.js
src/invoices/InvoiceLineForm/__snapshots__/InvoiceLineForm.test.js.snap

https://folio-org.atlassian.net/browse/UINV-567
https://folio-org.atlassian.net/browse/UINV-568
Introduce a new special field in the form to resolve the type of form submitted, that will specify handlers for each type.
https://github.com/user-attachments/assets/d2bff125-c37f-4e68-a0fb-12656c29c4b7
Ideally all of the PRs involved in breaking changes would …

UINV-567 UINV-568 Update submit actions in the invoice and invoice line forms

---

src/invoices/InvoiceDetails/InvoiceLines/InvoiceLinesActions.js
src/invoices/InvoiceForm/InvoiceForm.js
src/invoices/InvoiceForm/__snapshots__/InvoiceForm.test.js.snap
src/invoices/InvoiceLineForm/InvoiceLineForm.js
src/invoices/InvoiceLineForm/__snapshots__/InvoiceLineForm.test.js.snap

https://folio-org.atlassian.net/browse/UINV-567
https://folio-org.atlassian.net/browse/UINV-568
Keep inside `<Paneset>` only `<Pane>` components to resolve issue with layout spreading. …

UINV-567 Place `<form>` inside `<Pane>` component

---

CHANGELOG.md
package.json

https://folio-org.atlassian.net/browse/UINV-583
https://folio-org.atlassian.net/browse/UINV-584

UINV-583 UINV-584 Migrate react-intl and stripes dependencies

---

src/invoices/InvoiceForm/InvoiceFormContainer.js
src/invoices/InvoiceLineForm/InvoiceLineFormContainer.js

https://folio-org.atlassian.net/browse/UINV-567
Init PR: #851 
https://github.com/user-attachments/assets/fcd72ccf-6aeb-45c9-bd2e-bbea68429353 …

UINV-567 Restart form after submit and keep editing

---

src/invoices/VersionHistory/InvoiceVersionHistory/VersionHistory.js
src/invoices/VersionHistory/InvoiceVersionHistory/VersionHistoryView/VersionHistoryView.js
src/invoices/VersionHistory/InvoiceVersionHistory/VersionHistoryView/VersionHistoryViewInformation/VersionHistoryViewInformation.js

UINV-553 invoice history - minor improvements

---

CHANGELOG.md
src/common/utils/fetchInvoiceLines/fetchInvoiceLines.js
src/common/utils/fetchInvoiceLines/fetchInvoiceLines.test.js
src/common/utils/fetchInvoiceLines/index.js
src/common/utils/index.js
src/common/utils/invoiceUtils.js
src/invoices/InvoicesList/ExportSettingsModal/utils/fetchInvoiceLinesExportDataByIds.js
src/invoices/InvoicesList/ExportSettingsModal/utils/fetchInvoiceLinesExportDataByIds.test.js
src/invoices/InvoicesList/ExportSettingsModal/utils/getExportData.js

https://folio-org.atlassian.net/browse/UINV-572
Make sure to fetch all invoice lines per invoice not just 1000. Instead of fetching 1000 invoice lines now `fetchAllRecords` is being used which keeps fetching data until response is empty array 
https://github.com/user-attachments/assets/56d3ddae-a480-4cef-b384-8ab9686190ac
Ideally all of the PRs involved in …

UINV-572 Fetch all invoice lines per invoice on export

---

CHANGELOG.md
src/common/hooks/useInvoiceLineMutation/useInvoiceLineMutation.js

Update error handling in invoice creation to correctly extract the response object from ky’s error. This ensures compatibility with recent changes in `showUpdateInvoiceError`, where the response object is no longer automatically destructured.
https://folio-org.atlassian.net/browse/UINV-571
Previously, the frontend passed the entire error object, assuming the response was already extracted. However, changes in PR #809 modified `showUpdateInvoiceError` to require explicit destructuring. This PR ensures that `reason.response` is correctly passed instead of the whole reason object, aligning with the expected structure.
This is what response looks like
```
{
"name": "HTTPError",
"response": {
"body": { "locked": false },
"bodyUsed": false,
"headers": {},
"ok": false,
"redirected": false, …
```

UINV-571 Extract response from ky's error object when creating invoice lines

---

src/invoices/InvoiceDetails/Information/Information.js

UINV-470 undo hiding calculated exchange rate on invoice view

---

CHANGELOG.md
src/invoices/InvoicesList/hooks/useBuildQuery/useBuildQuery.js
src/invoices/InvoicesList/hooks/useBuildQuery/useBuildQuery.test.js

UINV-603 Fix Tags filter query to avoid global OR

---

CHANGELOG.md
src/invoices/InvoicesList/ExportSettingsModal/utils/createExportReport.js
test/jest/fixtures/exportReport.js

https://folio-org.atlassian.net/browse/UINV-604 …

UINV-604 fix invoice fund distr column in csv export

---

src/invoices/InvoicesList/ExportSettingsModal/utils/createExportReport.js
src/invoices/InvoicesList/ExportSettingsModal/utils/getExportData.js

UINV-604 fix data for invoice fund dist csv export column
